### ISSUE TITLE
Some moments

### ISSUE THREAD

**Issue by GishaSeven** [piotrulos/MSCModLoader#1]
1.  C:\Users\User\AppData\LocalLow\Royal John Love\My Summer Car - it is old MSC save folder(from 172 build). Now it: C:\Users\User\AppData\LocalLow\Amistech\My Summer Car
Pic: http://i.imgur.com/Fs4dhtH.png
2. Please, make console screen bigger(for plugins developers)
Pic: http://i.imgur.com/vmYgGC9.jpg

**Comment by piotrulos** [comment]
1. You are right, I still have both folders in `AppData\LocalLow` and forget about that there was change. Will fix that in small update.

2. Got it. I think I will add another keybind for this. For example: `~` opens normal console, `ctrl + ~` makes console bigger.
