### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by Shazuli** [piotrulos/MSCModLoader#10]
***Hi!***

Got the loader working and installed one mod at first. I then installed more, but when I installed *[IRLClock](http://www.racedepartment.com/threads/plugin-irlclock-timeplayed.135134/)* all the mod tabes had been shifted downwards. So the top most thing (console tab) opened the one underneath (settings tab I think), and that tab opened the one under that until it hit the bottom which did open the correct tab.
This is probably nothing because it was for MSCModLoader 0.1 (it had the old style window). I tried removing and re-adding it multiple times but always same result. This bug report can probably be ignored as it wasn't so popular on RD and was made for older version of mod loader. Just wanted you to know.

**Comment by piotrulos** [comment]
Cannot reproduce this bug. For me this mod works normally. Can you post screenshot of this bug?

**Comment by Shazuli** [comment]
![msc_pic29](https://user-images.githubusercontent.com/9884180/27509272-27de9ae2-58f9-11e7-828d-9d35c58c055c.png)
![msc_pic30](https://user-images.githubusercontent.com/9884180/27509275-27df6ab2-58f9-11e7-8b47-bdc1ce6732a3.png)
![msc_pic31](https://user-images.githubusercontent.com/9884180/27509273-27de94f2-58f9-11e7-9c84-7c14da71386a.png)
![msc_pic32](https://user-images.githubusercontent.com/9884180/27509274-27df08e2-58f9-11e7-9757-093394f78537.png)

This does not happen when IRLClock isn't installed. I have tried with only using IRLClock as well as with mods as you can see here.
The one at the end of the list (in this case it's ShowWear mod) will open the right tab though.

**Comment by piotrulos** [comment]
looks weird, but I installed "IRL Clock" and can't reproduce, still looks normal. As you can see on screenshot below:
![looks normal](https://user-images.githubusercontent.com/4009096/27509497-951e689e-58fe-11e7-9df7-2c5f7e14ab24.png)

But it looks like resolution/scaling problem, maybe that's clue. I will try to find where is the problem, thanks.

**Comment by piotrulos** [comment]
Ok I found this bug, it was just incorrectly setting parent UI element when adding new buttons, and it ignores scaling UI.

Since this is small bug (not game breaking) it will be public when 0.3 will be realeased. 
Thanks.
