### ISSUE TITLE
MSCLoader Says a .dll isn't a mod

### ISSUE THREAD

**Issue by Jacencaedus** [piotrulos/MSCModLoader#102]
#### Info
* **Windows 10 1903 18362.476
* **64 bit
* **MSC Loader Version 1.1.4
* **Possible bug

#### Description
So I am currently trying to make a mod to freely rotate grabbed objects using the mouse when you press a button, however, in order to do this properly I need to disable the mouselook script attached to the player object in order to lock the camera in place.  It seems that trying to even look at the script seems to make the modloader think its not a mod.

[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/3854821/output_log.txt)

**Comment by Jacencaedus** [comment]
After some further investigation, it seems that it's not looking at the mouselook script that causes the issue, it's having a reference to Assembly-CSharp-firstpass.dll which is where the script I need to temporarily disable is stored

**Comment by piotrulos** [comment]
This reference won't be available for modders due to abuse of using steam library located in that file.   
 Just use Playmaker that enables and disables that script when entering menu.
