### ISSUE TITLE
Visual studio enterprise cannot install template

### ISSUE THREAD

**Issue by IvovdBruggen** [piotrulos/MSCModLoader#104]
#### Info
* **OS version/build:** Windows 10 ver 1909(18363.592)
* **Architecture:** 64 bit
* **MSCLoader version:** 1.1.5
* **Type of issue:** bug

#### Description
I can't install the template files on Visual Studio 2019 Enterprise, I have followed all the steps from the installation. However I am on a enterprise version because of connecting my IDE with my school network. I think the issue lies that it can't be run on enterprise but I currently cannot install visual studio community.

#### Attachments
[dd_VSIXInstaller_20200217000111_0d24.log](https://github.com/piotrulos/MSCModLoader/files/4211167/dd_VSIXInstaller_20200217000111_0d24.log)

**Comment by IvovdBruggen** [comment]
Just tested the .vsix for version 1.0.1, seems I can install that template fine on enterprise. Maybe with the building of the .vsix enterprise was ruled out for a reason?

**Comment by IvovdBruggen** [comment]
I seem to have fixed it by editing the VSIXmanifest file, I'll report my changes later.

**Comment by piotrulos** [comment]
1.0.1 is latest one, previously you tried 1.0 version.
But yeah target sku is only community. Enterprise is overkill.
