### ISSUE TITLE
 Visual studio community cannot install template

### ISSUE THREAD

**Issue by TribbleT** [piotrulos/MSCModLoader#105]
Hi piotrulos,

I need your help. I followed all steps of the installation: https://github.com/piotrulos/MSCModLoader/wiki/Install-Visual-Studio-for-MSCLoader

And now at his manual: https://github.com/piotrulos/MSCModLoader/wiki/Install-template-for-Visual-Studio 

The MSCLoader.Templates.visx cannot be installed in Visual Studio community: see log:

17.02.2020 12:49:36 - Microsoft VSIX Installer
17.02.2020 12:49:36 - -------------------------------------------
17.02.2020 12:49:36 - vsixinstaller.exe version:
17.02.2020 12:49:36 - 16.4.1057
17.02.2020 12:49:36 - -------------------------------------------
17.02.2020 12:49:36 - Command line parameters:
17.02.2020 12:49:36 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\tmesser\Downloads\MSCLoader.Templates.vsix
17.02.2020 12:49:36 - -------------------------------------------
17.02.2020 12:49:36 - Microsoft VSIX Installer
17.02.2020 12:49:36 - -------------------------------------------
17.02.2020 12:49:37 - Initializing Install...
17.02.2020 12:49:37 - Erweiterungsdetails...
17.02.2020 12:49:37 - 	Identifier         : MSCLoaderTemplates.Piotrulos.40e0e374-6a16-47ae-87f8-009138faa324
17.02.2020 12:49:37 - 	Name               : MSCLoader Templates
17.02.2020 12:49:37 - 	Author             : Piotrulos
17.02.2020 12:49:37 - 	Version            : 1.0
17.02.2020 12:49:37 - 	Description        : MSCLoader Templates for vs2017 and vs2019
17.02.2020 12:49:37 - 	Locale             : en-US
17.02.2020 12:49:37 - 	MoreInfoURL        : 
17.02.2020 12:49:37 - 	InstalledByMSI     : False
17.02.2020 12:49:37 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
17.02.2020 12:49:37 - 
17.02.2020 12:49:37 - 	SignatureState     : Unsigned
17.02.2020 12:49:37 - 	Unterstützte Produkte : 
17.02.2020 12:49:37 - 		Microsoft.VisualStudio.Community
17.02.2020 12:49:37 - 			Version : [15.0,16.0]
17.02.2020 12:49:37 - 
17.02.2020 12:49:37 - 	Verweise           : 
17.02.2020 12:49:37 - 	Voraussetzungen    : 
17.02.2020 12:49:37 - 		-------------------------------------------------------
17.02.2020 12:49:37 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
17.02.2020 12:49:37 - 		Name         : Visual Studio core editor
17.02.2020 12:49:37 - 		Version      : [15.0,17.0)
17.02.2020 12:49:37 - 
17.02.2020 12:49:37 - Signaturdetails...
17.02.2020 12:49:37 - 	Extension is not signed.
17.02.2020 12:49:37 - 
17.02.2020 12:49:37 - Er wird nach passenden Produkten gesucht...
17.02.2020 12:49:37 - Installiertes Produkt gefunden - Globaler Pfad
17.02.2020 12:49:37 - Installiertes Produkt gefunden - Visual Studio Community 2019
17.02.2020 12:49:37 - VSIXInstaller.NoApplicableSKUsException: Diese Erweiterung kann auf den derzeit installierten Produkten nicht installiert werden.
   bei VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

I dont know but at according the internet the problem is the ")" at "[15.0,17.0)". Can you change it to "]" maybe?
Thank you for answer the issue!
An sorry for my bad english :)

Best regards Titus

**Comment by piotrulos** [comment]
download latest version of templates (from 1.1.5 release) not old one, old one works only for 2017.
