### ISSUE TITLE
Please describe how long an mod id should be 

### ISSUE THREAD

**Issue by TheHeroCraft1579** [piotrulos/MSCModLoader#107]
Can you please describe how i can make a mod id to verify it at you site.

**Comment by piotrulos** [comment]
Buy game first.

**Comment by TheHeroCraft1579** [comment]
> Buy game first.

I already bought it.

**Comment by piotrulos** [comment]
> 
> I already bought it.

Yeah sure, so why are you distributing cracked files on mod sites? Do you want a dmca claim on you?

**Comment by piotrulos** [comment]
but you distributed it instead of keeping it for yourself, which is against license terms you accepted.
Don't except any support from me if you will keep distributing illegal stuff.

**Comment by DonnerPlays** [comment]
xD
