### ISSUE TITLE
most mods lost compatibility with the new update

### ISSUE THREAD

**Issue by mezerek2000** [piotrulos/MSCModLoader#108]
Please read FAQ before!
#### Info
* **OS version/build: windows 7
* **Architecture:64 bit
* **MSCLoader version:1.1.6
* **Type of issue:** bug

#### Description
Basically after updating to 1.1.6 many mods lost compatibility and the console either throws an error that mods are compatible with earlier (1.1.5) version and the current one is invalid and I have to contact the author of a specific mod or the console says that mods threw too many error and were disabled

#### Attachments
I'm attaching an output log from mysummercar_data
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/4365593/output_log.txt)

**Comment by piotrulos** [comment]
Spam kunedo to fix his mod, because he was an idiot who put version number in his mods, instead using proper tools.
