### ISSUE TITLE
It keeps sending to many errors

### ISSUE THREAD

**Issue by ILikeToRuinPeoplesDay** [piotrulos/MSCModLoader#110]
Please read FAQ before!
#### Info
* **Windows 10** (ex. Windows 10 1709 16299.248)
* **64 bit
* **1.1.6
* **It sends to many errors so msc loader disables it

#### Description
I installed MSC Loader 1.1.6 because it said it was meant for that version. Then i loaded My summer car with the mod already installed. I clicked continue and it said DonnerTechSupercharger sent to many errors it has been disabled or whatever.

#### Attachments
Please attach **output_log.txt** from `mysummercar_Data` folder 
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/4396692/output_log.txt)
 
Screenshoots related to your issue.

**Comment by piotrulos** [comment]
Report that to mod author not me.
