### ISSUE TITLE
Command line version?

### ISSUE THREAD

**Issue by Krutonium** [piotrulos/MSCModLoader#112]
Please read FAQ before!
#### Info
* **OS version/build:** (ex. Windows 10 1709 16299.248)
Arch Linux
* **Architecture:** (32 or 64 bit?)
64 Bit
* **MSCLoader version:** (ex. v0.4)
Any

#### Description
WPF isn't usable on Linux, but My Summer Car *is*, technically. I was hoping it would be possible for you to make a command line version of the patcher so that I could install the modloader on my copy without having to copy everything to a Windows Box and back.

**Comment by piotrulos** [comment]
there is no wpf used there at all. Just use proton like msc and you are fine.

**Comment by Krutonium** [comment]
Sorry! I swear the last time I tried this (Right before I posted this in fact!) the console informed me it was using WPF :/

**Comment by piotrulos** [comment]
Just look at code next time https://github.com/piotrulos/MSCModLoader/tree/master/MSCPatcher/MSCPatcher it's raw c#, there is no xaml stuff.    

IF you want you can port it as long as you follow GPL-3 license.     

For me rewriting 90% of code is not worth time for 0.1% of msc userbase.
