### ISSUE TITLE
Stutters and pauses? (Issue also on Nexusmods)

### ISSUE THREAD

**Issue by JDTractorz** [piotrulos/MSCModLoader#114]
#### Info
* **OS version/build:** Windows 7 Ultimate SP1 (I think it's build 7601)
* **Architecture:** 64 Bit
* **MSCLoader version:** 1.1.7
* **Type of issue:** bug

#### Description
I keep getting stutters and pauses in game with the MSCLoader installed. It happens with or without mods. What happens is that I get random pauses for a second or two when moving around, often repeating 3 or 4 times in a row. Adding any mods just makes the problem worse. It also happens when I say anything or flip a bird (lol)

I would just play with it because it's not really game breaking, but sometimes the pauses can be like 5 seconds long and happen in quick succession so it becomes unplayable.

I am running the latest version of My Summer Car (not experimental)

It keeps spamming an error in the log, not sure what it is.

I originally posted this on Nexusmods but did not get a response so I posted it here.
#### Attachments
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/4639039/output_log.txt)

**Comment by piotrulos** [comment]
did you try basic steps listed in bugtracker? Like verify game files on steam, try on new save file

**Comment by JDTractorz** [comment]
I tried verifying steam files, and that does nothing other than wipe out the mod loader.

As for a new save, I used a fairly new save to test the mod loader out in before, but as soon as I tried creating a new save with or without mods the game locks up and throws an error in the log.
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/4639144/output_log.txt)

**Comment by JDTractorz** [comment]
So I finally got in, its still stuttering on a fresh save. Same errors in log as the first post. I can still post it if u want.

**Comment by piotrulos** [comment]
seems not related any way to modloader, it just throws directx errors.
```
HandleD3DDeviceLost
  HandleD3DDeviceLost: still lost
Skipped frame because GfxDevice is in invalid state (device lost)
```
This may be issue on drivers level, or hardware level.

**Comment by JDTractorz** [comment]
I'm running latest AMD drivers, and this is a fairly new card (year old) so I don't think it is drivers or hardware.

That error only appears in the second log, and that occurred before I properly reinstalled the mod loader.

It keeps spamming the error 
"Index is less than 0 or more than or equal to the list count.

Parameter name: index

0
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

Several ArrayList Proxies coexists on the same GameObject and no reference is given to find the expected ArrayList
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
"

That error you posted above does not appear in my latest log.
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/4640808/output_log.txt)

**Comment by piotrulos** [comment]
That error was in game forever (It's up to msc dev to fix it) so it's not this. 
That last log is too short, you need to actually play until your freezing happens then it will be proper log.

**Comment by JDTractorz** [comment]
It did happen, thats the thing. It stuttered a few times and every time that error came up when it stuttered (roughly)

**Comment by piotrulos** [comment]
MSC is spaghetti garbage in terms of development. But what you pasted is just message about array list, happens in normal game without modloader.

**Comment by JDTractorz** [comment]
So there's no real way to tell what is causing the stutters?

**Comment by piotrulos** [comment]
Only first log had clue about gfxdevice. Other ones has nothing related that could cause stutters.
