### ISSUE TITLE
Acces denied error

### ISSUE THREAD

**Issue by bfgelectronics** [piotrulos/MSCModLoader#115]
Please read FAQ before!
#### Info
* **OS :**Windows 10
* **Architecture:** x64
* **MSCLoader version:**  v1.1.7
* **Type of issue:** crash
#### Description
Every time i try to patch the game, it says that acces is denied, even if i run with administrator priviledges.

#### Attachments
Please attach **output_log.txt** from `mysummercar_Data` folder  : i dont have any file like these in that folder.
https://imgur.com/a/Exmd5qx

**Comment by bfgelectronics** [comment]
I dont see anythink like these on faq

**Comment by piotrulos** [comment]
Literaly says that pirated/modified versions are not supported.
