### ISSUE TITLE
can't open MSC MOD loader

### ISSUE THREAD

**Issue by grihavtg** [piotrulos/MSCModLoader#116]
When i just click on msc mod loader or patcher there is unknow issue with only red strike.
I tried 1.1.7 version and 0.3.5 version - all same, can you help me pleas.
![bandicam 2020-08-16 21-06-06-405](https://user-images.githubusercontent.com/69764338/90339811-88edd380-e004-11ea-9bde-c12152950576.jpg)
System: i7 2600k
             rx 580 8 gb
             12 gb ddr3 1600mhz
OC: Windows 7 64 bit

**Comment by piotrulos** [comment]
seems like your os has corrupted .net framework install

**Comment by grihavtg** [comment]
Piotrulos VERY BIG THANKS for You. I reinstalled framework and all now works great, thanks:)
