### ISSUE TITLE
MSC loader crashing

### ISSUE THREAD

**Issue by KIWIshot** [piotrulos/MSCModLoader#121]
[MSCLOADER_CRASH.txt](https://github.com/piotrulos/MSCModLoader/files/5898081/MSCLOADER_CRASH.txt)
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/5898088/output_log.txt)

#### Info
* **OS version/build: ex. Windows 10 1909 18363.1316)
* **Architecture: 64 bit
* **MSCLoader version: v1.1.10

* **Type of issue: crashing

**Comment by piotrulos** [comment]
try reinstalling it, click Remove Modloader and then click Install Modloader again.

**Comment by KIWIshot** [comment]
> try reinstalling it, click Remove Modloader and then click Install Modloader again.

I try it and I also try to run MSC patcher as administrator and nothing change

**Comment by KIWIshot** [comment]
bro I fix it by instaling version 1.1.8 
but thanks for your offer to help me :)

**Comment by piotrulos** [comment]
That's not a fix, since for whatever reason your config file isn't updated. 
Are you unpacking all files correctly from zip folder?

**Comment by KIWIshot** [comment]
I know this isn't a fix but I think I have an older version of MSC(crack from 14.1.2021) and that's the problem
