### ISSUE TITLE
Unable to launch MSCPatcher to install Modloader, Access to path '...\MSCLoader\Log.txt' is denied

### ISSUE THREAD

**Issue by TwinMinds** [piotrulos/MSCModLoader#122]
Please read FAQ before!
#### Info
* **OS version/build:** Windows 10 2004 19041.746
* **Architecture:** 64 bit
* **MSCLoader version:** Version 1.1.11
* **Type of issue:** Unable to launch MSCPatcher to install Modloader, Access to path '...\MSCLoader\Log.txt' is denied

#### Description
I am unable to launch MSC Patcher getting the above error.  I have fully reinstalled the game, and deleted any old mods and old versions of MSC Patcher before fully extracting the latest 1.1.11 zip from your git releases.  I have verified the folder is not marked read-only, and all users have full permissions to the folder and path.  I have tried running MSC Patcher as admin but get the same error.  There is no log.txt file being generated, nor included in the MSCLoader.full.package.zip file.  I have tried creating a blank log.txt file but get the same error.

I have no output_log.txt file to provide since the mod loader can't install/run to generate the file.

#### Attachments
Please attach **output_log.txt** from `mysummercar_Data` folder  

![image](https://user-images.githubusercontent.com/64905062/107413799-c8d6d480-6ad6-11eb-9231-79df69b3b8aa.png)

**Comment by piotrulos** [comment]
Don't unpack it to mods folder, don't unpack it into system protected folders.
Simple instructions to follow in readme, description etc. But people still fails them.

**Comment by TwinMinds** [comment]
Documents isn't a system protected folder, and it's not a mods folder.  I have unpacked into a folder that is perfectly acceptable to use, and has worked in the past, but does not work in this version.

**Comment by piotrulos** [comment]
Documents/MySummerCar IS a mods folder that can be choosed. 
But whatever if you know better then good liuck.

**Comment by TwinMinds** [comment]
The mods folder is listed as Documents/MySummerCar/Mods, so I didn't unpack to that folder, installing up a level should work fine, and has worked fine in the past for previous versions of ModLoader.  I have read countless of your documentations and never once did it say not to install into that folder.  It only says "Save it into any folder you want (DO NOT put it in game files)".  Knowing now that there's an arbitrary limitation of which folder to install to, I've picked another folder entirely and that worked fine.

If you want to tell people to read the directions, make sure the directions are correct.

**Comment by piotrulos** [comment]
since like 5 last versions nothing changed at all in installation method, problem is on your side. Just use any other folder if your current one have weird broken permissions.
