### ISSUE TITLE
MSCLoader doesn't start and only shows "Test" loading a save

### ISSUE THREAD

**Issue by FedeArre** [piotrulos/MSCModLoader#124]
#### Info
* **OS version/build:** Windows 10 Pro 10.0.19042
* **Architecture:** 64bit
* **MSCLoader version:** 1.1.12
* **Type of issue:** Bug

#### Description
I was normally playing and decided to install some mods (FifthGear and DonnorTech ECU), after installing both the game refused to load the savegame with the message "Test" (shown in the photo). Also i noticed that the Mod settings button and the console disappeared. I uninstalled both mods but the game is still in the same state. I'm using the last experimental version. I also tried removing all my mods but this didn't help,

Edit: Reinstalling MSCLoader seems to fix the problem. I'm not gonna close the issue because i want to know what triggered that state.
#### Attachments
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/6098344/output_log.txt)
![Main screen](https://user-images.githubusercontent.com/39017587/110262020-08d38f00-7f91-11eb-9f12-42b4f7cea025.png)
![Attempting to load my savefile](https://user-images.githubusercontent.com/39017587/110262022-0a04bc00-7f91-11eb-93cc-fe1698ec9803.png)

**Comment by piotrulos** [comment]
try reinstall in patcher, click "remove mscloader" and then click "install modloader".
