### ISSUE TITLE
wine crashes modloader 1.1.8 and 1.1.12 on wine

### ISSUE THREAD

**Issue by slowpoke9292** [piotrulos/MSCModLoader#125]
Please read FAQ before!
#### Info
* **OS version/build:** wine 6.0.0 ran on debian 10 buster
* **Architecture:** 64-bit 
* **MSCLoader version:** 1.1.8 and 1.1.12
* **Type of issue:** crashes upon load.

#### Description
the main menu works but after i try to load my save, the game crashes with no crash report or output.log file and im not sure how to fix it. how do i get this fixed?
#### Attachments
(no output.log generated for some reason)

**Comment by slowpoke9292** [comment]
(FYI: i tried to use MOP by itself to no avail.)

**Comment by piotrulos** [comment]
for linux related stuff ask in pinned issue.
