### ISSUE TITLE
Game freezes when I use MSCLoader

### ISSUE THREAD

**Issue by Sidneeeeey** [piotrulos/MSCModLoader#126]
Please read FAQ before!
#### Info
* **OS version/build:** Windows 10 1909 18363.1440
* **Architecture:** 64 bit
* **MSCLoader version:** 1.1.12
* **Type of issue:** Game freezes

#### Description
After MSCLoader is installed and I press Play! in the MSC Configuration, the screen turns black and when I click on it, it crashes.
The game stays on a black screen and won't change.
I've tried playing it without MSCLoader and than it did work again.
Before all this happened, it did work for months.

#### Attachments
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/6183253/output_log.txt)

Screenshoots related to your issue.

**Comment by piotrulos** [comment]
Log you provided is from umnodified vanilla game.

Include log when crash happens.

**Comment by Sidneeeeey** [comment]
This is the only other file I could find.

[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/6184499/output_log.txt)

**Comment by piotrulos** [comment]
In both ones you don't have modloader installed. So are you correctly installed one?

**Comment by Sidneeeeey** [comment]
It says it is.

![MSCPatcher2](https://user-images.githubusercontent.com/81174606/112179499-090f9380-8bfb-11eb-823a-e7583128bea4.png)

**Comment by piotrulos** [comment]
make sure to grab output_log.txt from main folder (where mysummercar.exe is)

**Comment by Sidneeeeey** [comment]
The first output.log I send was the one from the msc_data folder and the second output.log was the one from the main folder.
I can see that it updates everytime I start up Msc but compared with the earlier version I did send there is no differents.

**Comment by piotrulos** [comment]
so idk. 
You should try clean mscloader install, click remove mscloader then verify msc game files on steam and install mscloader again.

**Comment by Sidneeeeey** [comment]
I've tried that like 5 times but it just won't work, I even did reinstall the game a couple of times.

**Comment by piotrulos** [comment]
well without proper log or crash dump I can't help, because without it you can only guess what is wrong.
