### ISSUE TITLE
Allow to run steamless

### ISSUE THREAD

**Issue by Kreyren** [piotrulos/MSCModLoader#128]
Please read FAQ before!
#### Info
* **OS version/build:** ZernitOS Renux/RXT, Alpha build
* **Architecture:** AMD64 on Xen
* **MSCLoader version:** v1.1.14
* **Type of issue:** suggestion

#### Description
I have non-standard system where proton gives me terrible efficiency and fails it's runtime on steam's proton due to close and monopolistic ecosystem of Valve (https://github.com/ValveSoftware/Proton/issues/2900).

#### Proposal
Allow to run the MSCLoader steamless on demand

![image](https://user-images.githubusercontent.com/11302521/117348863-074c1780-aeab-11eb-82ac-99be4d02154c.png)

**Comment by piotrulos** [comment]
You don't need to use that button. You can just run game as always.

**Comment by Kreyren** [comment]
> You don't need to use that button. You can just run game as always.

Did that, says installed, but seems to not work assuming that i don't have this UI in the game:

![image](https://user-images.githubusercontent.com/11302521/117441096-2ee7c200-af35-11eb-88d4-3e6923e8f84f.png)

**Comment by piotrulos** [comment]
because linux is not officially supported. Linux tutorial is in pinned issue, and there should be asked questions.
