### ISSUE TITLE
MSCPatcher Stops working evey time I try activating it 

### ISSUE THREAD

**Issue by BronyofMarz** [piotrulos/MSCModLoader#13]
Evey time I try running the patcher it stops working instantly as soon as I click I don't know whats happening and the "error log" created by windows deletes before i have a chance to read it. Plz Help

**Comment by piotrulos** [comment]
More info please:   
what OS do you have? do you unpack zip file before running patcher? What error it shows?   
  
I'm not a mind reader, please provide more helpful informations, attach screenshots etc.

**Comment by BronyofMarz** [comment]
windows 7, yes Ive unpacked it before running, and today after trying to open it again nothing is working the waiting hourglass shows up and then nothing happens not even the error message from yesterday.

**Comment by piotrulos** [comment]
Do you have .Net framework 4 installed correctly? https://www.microsoft.com/en-us/download/details.aspx?id=17851 maybe try this to reinstall.

**Comment by BronyofMarz** [comment]
it says I have everything installed correctly and still nothing is happening and Ive tried downloading MSC again with the same result  
![img_6132 1](https://user-images.githubusercontent.com/30789068/29084220-f1f8bfe2-7c30-11e7-939e-a34b0e944773.JPG)

**Comment by BronyofMarz** [comment]
And Ive tried to use the old 0.1 and it doesn't work 
![img_6133 1](https://user-images.githubusercontent.com/30789068/29084549-fa949080-7c31-11e7-9d95-f52fd15d9a8d.JPG)

**Comment by BronyofMarz** [comment]
[WERB664.tmp.appcompat.txt](https://github.com/piotrulos/MSCModLoader/files/1208970/WERB664.tmp.appcompat.txt

These are the Temp Error Logs I wasn't able to show you before for 0.2

**Comment by piotrulos** [comment]
Do not mess 0.1 with 0.2 it won't work.
And do not unpack 0.2 files in game folder (like 0.1), unpack 0.2 files for example on Desktop and then run MSCPatcher.exe  also try to right click on exe and "Run as Administrator"

**Comment by BronyofMarz** [comment]
I followed your rules i just wanted to test 0.1 to see if it worked and I've tried to run 0.2 as admin and nothing happens

**Comment by piotrulos** [comment]
You should try to delete entire `Managed` folder from `mysummercar_Data`, and go to properties of the game in steam and under Local Files click check game integrity files (or something like that) this will download clean dlls (maybe something messed up)   
  
Also download clean copy again of MSCLoader https://github.com/piotrulos/MSCModLoader/releases/download/v0.2.3/MSCLoader.zip and then try to run it.   
   
If this crashes again then something wrong is on your side. You should attach windows crash logs from here: `C:\Users\All Users\Microsoft\Windows\WER\ReportQueue` or here `C:\Users\All Users\Microsoft\Windows\WER\ReportArchive` (find these with MSCPatcher.exe in name) That file you posted above is some loaded dll database, not a crash/error log.

**Comment by BronyofMarz** [comment]
ok I checked the wer files and I only had two windows update failures and no MSCpatcher ones. so I went to my task manager to see if i could get the pachers process to show up and it did but it ends instantly with another process call werfault.exe. so I doubt I'm gonna get to use your mod any time soon. I'm sorry if im wasting your time pio.

**Comment by BronyofMarz** [comment]
I fixed it man my Net Framework was OutofDate
