### ISSUE TITLE
Issue with AddSlider

### ISSUE THREAD

**Issue by MLDKYT** [piotrulos/MSCModLoader#130]
Please read FAQ before!
#### Info
* **OS version/build:** Windows 10 Pro 20H2
* **Architecture:** 64 bits
* **MSCLoader version:** 1.1.14
* **Type of issue:** bug

#### Description
I am making a mod and I am stuck in an issue that a slider always returns the value 0.

#### Attachments
Please attach **output_log.txt** from `mysummercar_Data` folder  
here [output_log.txt](https://github.com/piotrulos/MSCModLoader/files/6437295/output_log.txt)
Screenshoots related to your issue.
![photo1](https://user-images.githubusercontent.com/59791284/117357627-79295e80-aeb5-11eb-9daf-9be838f61d60.png)
![photo2](https://user-images.githubusercontent.com/59791284/117357590-6f076000-aeb5-11eb-8005-f5ad0445531a.png)
![photo3](https://user-images.githubusercontent.com/59791284/117357658-81819980-aeb5-11eb-8e52-196cc0d1387c.png)

**Comment by piotrulos** [comment]
In what function you try to read a value?

**Comment by MLDKYT** [comment]
UpdateAllSettings (when it changes)

**Comment by piotrulos** [comment]
So I copied that code you posted and it works without issue

![obraz](https://user-images.githubusercontent.com/4009096/117443629-b5ea6980-af38-11eb-95db-6375e785b640.png)

**Comment by MLDKYT** [comment]
Found it: Running new Settings() in ModSettingsLoaded() event function was the issue.
