### ISSUE TITLE
Settings don't work as intended

### ISSUE THREAD

**Issue by ensimed** [piotrulos/MSCModLoader#131]
#### Info
* OS version/build:  Windows 10 2004 19041.928
* Architecture: 64bit
* MSCLoader version: 1.1.12 or later
* Type of issue: bug

#### Description
Mod settings do not work in game after 1.1.12 update, as you can see in the attached screenshot, the yellow box in the upper left corner appears, but not so the selected settings. Everything works as intended if I'm downgrading to 1.1.11

#### Attachments
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/6448096/output_log.txt)
[picX134](https://user-images.githubusercontent.com/69088479/117581263-3907ed00-b0fc-11eb-8763-af8b582afed5.png)

**Comment by ensimed** [comment]
btw, ik this is already 1.1.14, but it first happened as of version 1.1.12

**Comment by piotrulos** [comment]
Do you have "fifth gear" installed? Because that mod is known for breaking settings UI.

**Comment by ensimed** [comment]
Yes

**Comment by piotrulos** [comment]
It's up to you.
I heard that there will be update to fifth gear that fixes UI issues, but don't know when.

For now I'm closing this issue since it's mod related instead of modloader.
