### ISSUE TITLE
MSCLoader not finding mods

### ISSUE THREAD

**Issue by Daddy-Kermit** [piotrulos/MSCModLoader#132]
**Info**
**OS version/build:** WIN10 20H2 19042.1055
**Architecture:** 64x
**MSCLoader version:** 1.1.1
**Description**
MSCLoader not finding mods, output log says 0 mods detected, however has correct file location, reinstalled MSCLoader twice, reinstalled all mods twice, checked mods one at a time, nothing changed. only variables i can think of is custom file music, but that is all.

**Attachments**
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/6686346/output_log.txt)
**Screenshoots related to my issue.**
![image](https://user-images.githubusercontent.com/86236345/122756626-82933e00-d24b-11eb-8520-4477ce2a3272.png)
![image](https://user-images.githubusercontent.com/86236345/122756764-b2424600-d24b-11eb-8734-bc73536e58e2.png)

**Comment by piotrulos** [comment]
Look first where you reporting shit. This is not bloatloader pro dev.

**Comment by Daddy-Kermit** [comment]
hey, no need to be an ass about it, it was an honest mistake, but thank you for your quick response and sorry about the inconvenience
