### ISSUE TITLE
I can't download the asset bundle project

### ISSUE THREAD

**Issue by tommojphillips** [piotrulos/MSCModLoader#136]
Hey piotrulos, i've tried downloading the asset bundle project but unable to download, would you be able to give me a link? cheers

**Comment by tommojphillips** [comment]
nevermind! quick google search gave me exactly what i was after:

`using UnityEditor;
 
public class CreateAssetBundles {
 
	[MenuItem ("Assets/Build AssetBundles")]
	static void BuildAllAssetBundles ()
	{
		BuildPipeline.BuildAssetBundles ("Assets/AssetBundles", BuildAssetBundleOptions.None, BuildTarget.StandaloneWindows64);
	}
}`

**Comment by piotrulos** [comment]
Download links are currently reworked, because of 1.2 release soon.
