### ISSUE TITLE
OnLoad is only called once

### ISSUE THREAD

**Issue by mattcode55** [piotrulos/MSCModLoader#14]
`Mod.OnLoad` is only called once, when the game loads.

It would be useful if it was called whenever the player spawned in (new game, continue) so that mods that edit things in the game world worked every time instead of just once.

**Comment by piotrulos** [comment]
This will change in 0.3, and acutally it works in experimental state.
When you go back to main menu it will reload everything, and OnLoad will be called again when "continue" or "new game"

**Comment by mattcode55** [comment]
Sorry I didn't notice that this feature was added. Thanks :)
