### ISSUE TITLE
Fatal error messages and the game is not detecting save files.

### ISSUE THREAD

**Issue by sluck1337** [piotrulos/MSCModLoader#144]
#### Info
* **OS version/build:** Windows 10 Pro 21H2
* **Architecture:** 64 bit
* **MSCLoader version:** v1.2.5
* **Type of issue:** bug

#### Description
Yesterday the game was fine, but today when I started it I saw those error messages linked below and the game is not detecting my save files. I tried reinstalling the loader, the game and I deleted my saves and mods but nothing changed.

#### Attachments
https://anonfiles.com/LcO6s4W8x6/logs_rar
https://images.sluck.hu/1T1YRRF5 ; https://images.sluck.hu/6Yu7kLt0

**Comment by sluck1337** [comment]
By the way the issue still remains if I uninstall the loader.

**Comment by piotrulos** [comment]
Make sure you are using correct path for msc.

**Comment by sluck1337** [comment]
I am using the correct path of course, but now it's uninstalled but I still get the messages. I uninstalled the game and the loader too but I still get the message lmao

**Comment by piotrulos** [comment]
Are you sure? what does patcher log says after you uninstalled it?

**Comment by sluck1337** [comment]
What do you mean? I just deleted the patchers folder.

**Comment by piotrulos** [comment]
wtf? You just removed installer, not mod loader.

To install/reinstall/remove you need to run patcher and select option to do it.

**Comment by sluck1337** [comment]
LMFAO, I am literally blind I didn't see that option. By the way a PC restart solved the problem.
