### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by AbsoluteAnton** [piotrulos/MSCModLoader#145]
Please read FAQ before!
#### Info
* **OS version/build: file: Arch Linux x86_64
* **Architecture: 64 bit
* **MSCLoader version: v 1.2.5
* **Type of issue:  crash / bug

#### Description
When i try to install the MSCLOADER on linux i cannot find the documents folder or the appdata folder. Where are these located?
The linux tutorial on the github doesent work for some reason.

**Comment by piotrulos** [comment]
Linux problems/questions should be ask in #135
