### ISSUE TITLE
[Bug]: "Configure MSCLoader Mod" window cropped/too small

### ISSUE THREAD

**Issue by tlr08-dev** [piotrulos/MSCModLoader#148]
### OS version/build

Windows 7 Ultimate build 7601 Service Pack 1

### MSCLoader version

1.2.7

### Description

The "Configure MSCLoader Mod" window is cropped so you can't see the Done button or the Target dropdown. The window is not rezisable. Image is attached. You can still press the Done button by tabbing to it and pressing enter, so it is still usable. I am guessing this is a Windows 7 specific issue.

### Attachments

![window](https://user-images.githubusercontent.com/44274249/185766836-688ff846-07db-4bca-9e79-44ec213dbe8c.png)

**Comment by piotrulos** [comment]
Looks more like scaling issue, your font size is unnaturally big.

**Comment by tlr08-dev** [comment]
Yeah I have 125% scaling enabled. In my opinion I think the window size should still ajust to be able to fit all of the content.

**Comment by piotrulos** [comment]
On windows 7 scaling was broken.
Idk if I can fix that easily, since Visual Studio doesn't even metion windows 7 in it's sdk. (which is kinda expected since support ended few years ago).

**Comment by piotrulos** [comment]
I tried to replicate this issue, but can't on win10, it scales correctly.   
So to fix it I will need to create some machine with win 7 and replicate it there, and then find fix for it.  

Currently putting this issue on low priority backlog.

**Comment by ReptileTextile** [comment]
I have this same issue on Windows 11 Pro 21H2, Visual Studio 2022 Community Version 17.3.3. "Done" button is not displayed no matter which scaling option I select.
