### ISSUE TITLE
Can´t load AssetBundle

### ISSUE THREAD

**Issue by RalphCZ** [piotrulos/MSCModLoader#149]
### OS version/build

Visual Studio: Windows 7, My Summer Car: Windows 10

### MSCLoader version

1.2.7 build 274

### Description

Helo, i´m trying to load AssetBundle. In visual studio is no errors, but if i try this mod in game, i see this error: Object reference not set to an instance of an object in UnityEngine.AssetBundle LoadBundle(MSCLoader.Mod, System.string). I Have copied unity3d file of this mod to correct folder

### Attachments

[output_log - kopie.txt](https://github.com/piotrulos/MSCModLoader/files/9401378/output_log.-.kopie.txt)
[MSCLoader_Preloader.txt](https://github.com/piotrulos/MSCModLoader/files/9401382/MSCLoader_Preloader.txt)

**Comment by piotrulos** [comment]
How does your LoadAssets.LoadBundle line looks like?

**Comment by RalphCZ** [comment]
This is my script:

             // Called once, when mod is loading after game is fully loaded
            AssetBundle ab = LoadAssets.LoadBundle(this, "radiomod.unity3d");
            GameObject go = ab.LoadAsset<GameObject>("ROSSIA_303.prefab");
            GameObject Pokur = GameObject.Instantiate(go);
            //REMEMBER to instantiate your object next.
            ab.Unload(false); //unload when you take all items you need.
            Pokur.name = "Pokur303";

**Comment by piotrulos** [comment]
Code looks correct.

I think the issue is unity3d file. Did you used unity 5.0.0 to compile that file? Can you open that file in asset studio to see if it opens there?

**Comment by RalphCZ** [comment]
i can open this file in Asset Studio, i created it with Unity 2019.

**Comment by piotrulos** [comment]
That's the issue, you can't use newer version on old version.
You need to download unity 5.0.0 exactly

**Comment by RalphCZ** [comment]
thanks
