### ISSUE TITLE
 Refusal to access the path

### ISSUE THREAD

**Issue by ErnestR** [piotrulos/MSCModLoader#15]
When i try to install ModLoader (after selecting MSC folder) the error appears : 
![przechwytywanie](https://user-images.githubusercontent.com/29142800/29654686-6f1a504c-88ae-11e7-88d2-c3e37bb29811.PNG)
The file with ModLoader is unpacked.

**Comment by piotrulos** [comment]
Looks like permission problem. Did you try run patcher as admin? Right click on patcher exe and select "Run as Administrator"

**Comment by ErnestR** [comment]
Yes i have tried with the administrator's permission and without, but the same error apperas :/

**Comment by piotrulos** [comment]
Try manually delete this file, looks like leftover from previous instalation.
Patcher will automatically copy new files from patcher folder.
