### ISSUE TITLE
[Bug]: crashes immediately on launch

### ISSUE THREAD

**Issue by staledorito** [piotrulos/MSCModLoader#152]
### OS version/build

Windows 10 21H2 19044.1889

### MSCLoader version

1.2.7

### Description

after the splash screen, the game simply crashes. i've removed mods which were throwing errors in the output log as well as uninstalling modloader pro.

### Attachments

[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/9437311/output_log.txt)
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/9437312/output_log.txt)
[error.log](https://github.com/piotrulos/MSCModLoader/files/9437313/error.log)
![erroinfo](https://user-images.githubusercontent.com/112230727/187014302-fe9de234-d0de-44a7-ab71-22fb7c9b5265.PNG)
[MSCLoader_Preloader.txt](https://github.com/piotrulos/MSCModLoader/files/9437314/MSCLoader_Preloader.txt)
![mods](https://user-images.githubusercontent.com/112230727/187014349-cc26c9d0-9f88-4a05-9f8b-e7a0bd114115.PNG)

**Comment by piotrulos** [comment]
Seems like one of your mods is causing this issue, Try running it without any mods.

You should try to do clean install mscloader, click "Remove MSCLoader" and then click "Install MSCLoader"   (verify game files on steam is also recommmended)
