### ISSUE TITLE
[Bug]: Error in creating project on VS2022

### ISSUE THREAD

**Issue by JGabrielGruber** [piotrulos/MSCModLoader#158]
### OS version/build

Windows 11 Pro 21H2 (22000.318)

### MSCLoader version

1.2.8

### Description

Hello everyone!

On a fresh windows install, I've been following the [docs](https://github.com/piotrulos/MSCModLoader/wiki/Install-Visual-Studio-for-MSCLoader) and it went pretty well, until the step where I should create a project.

As I give the project a name, when I click on create, a window error shows up with the following message:

Original:
```
---------------------------
Microsoft Visual Studio
---------------------------
O arquivo vstemplate faz referência à classe de assistente "VSIXProject1.WizardImplementation", que não existe no assembly "MSCLoader Templates, Version=1.2.0.0, Culture=neutral, PublicKeyToken=56373c2dca4c3ff7".
---------------------------
OK   
---------------------------
```

Translated:
```
---------------------------
Microsoft Visual Studio
---------------------------
The file vstemplate references the helper class "VSIXProject1.WizardImplementation", that does not exist in assembly "MSCLoader Templates, Version=1.2.0.0, Culture=neutral, PublicKeyToken=56373c2dca4c3ff7".
---------------------------
OK   
---------------------------
```

What can I do?

### Attachments

![image](https://user-images.githubusercontent.com/22822110/193344122-d483cd7a-cf57-4f6c-9334-c8ee3a0b5174.png)

**Comment by piotrulos** [comment]
Are you sure that you downloaded latest vs2022 templates? It should be complete with all references.

You can try to reinstall templates:

Open random empty project in vs, go to extensions > manage extensions and go to installed tab
then select mscloader templates and click uninstall, then try installing again vs2022 templates.

![obraz](https://user-images.githubusercontent.com/4009096/193349390-90a7d7a4-570e-4b11-96f3-58d7d3574d19.png)

**Comment by JGabrielGruber** [comment]
Hello, sorry for the delay,

Yes, I've download [this](https://github.com/piotrulos/MSCModLoader/releases/download/v1.2.8/MSCLoader.Templates.vs2022.vsix) template, then, removed it, installed an older version and still didn't get to work.

I did the steps, and still got the same error message.

**Comment by piotrulos** [comment]
Idk what could cause that, I cannot reproduce that issue even when uninstalling and installing again.

Only thing I can think of is that your VS install is incomplete.

**Comment by JGabrielGruber** [comment]
it's okay, what can I look for in my installation?

**Comment by piotrulos** [comment]
mostly if you have .net stuff installed.

Also there may be other possibility, if you installed VS on system drive, maybe try running VS as admin.

**Comment by JGabrielGruber** [comment]
I've rechecked my installation, all the stuff listed [here ](https://github.com/piotrulos/MSCModLoader/wiki/Install-Visual-Studio-for-MSCLoader) are installed:
- Game development with Unity without the optional
![image](https://user-images.githubusercontent.com/22822110/193356521-88b6a631-ad57-4e96-9343-7fa91cb2182c.png)
- .NET desktop development without the optionals
![image](https://user-images.githubusercontent.com/22822110/193356582-cf3eb06b-aedf-4d53-a755-fa427a1e7bfc.png)
- .Net Framework 3.5 development tools
![image](https://user-images.githubusercontent.com/22822110/193356690-a7673880-59b9-4b97-a94c-25195bf23873.png)
- .Net Framework 3.5 and 2.0 enabled
![image](https://user-images.githubusercontent.com/22822110/193356807-a7dc720a-1249-424c-90c8-05a399e23dab.png)

I've tried runing as admin and got the same error message

**Comment by piotrulos** [comment]
Wait, screenshot says that you have VS 16.11 which is VS2019 not VS2022

**Comment by JGabrielGruber** [comment]
Jesus Christ, I'm so much sorry

I'm using VS2019, I swear I tough that I downloaded the 2022 tough...

I'm sorry for wasting your time @piotrulos 
May your life be blessed my friend, you're a wonderful person, I hope that with time I can contribute to your work
