### ISSUE TITLE
[Bug]: VS 2022 There is no "Done" button in template config window.

### ISSUE THREAD

**Issue by Heworte-bin** [piotrulos/MSCModLoader#159]
### OS version/build

Windows 10, Visual Studio 2022

### MSCLoader version

Template version 1.2.1

### Description

I want to create a project and when the template config window appears, I can't go further. There is no “Done” button.
Btw. Sorry for my bad English.

### Attachments

![Zrzut ekranu (28)](https://user-images.githubusercontent.com/118050952/205713352-40c2b4f8-9a4a-4636-bf05-f1acd45606d0.png)

**Comment by piotrulos** [comment]
this is scaling issue, make sure you are on 100% scaling. (or just press enter

**Comment by Heworte-bin** [comment]
Thanks. I will check the scaling.

pon., 5 gru 2022, 19:44 użytkownik piotrulos ***@***.***>
napisał:
