### ISSUE TITLE
[Bug]: Loader keeps directing mod folder to OneDrive

### ISSUE THREAD

**Issue by PeasIn** [piotrulos/MSCModLoader#163]
### OS version/build

Windows 11 22H2

### MSCLoader version

1.2.10

### Description

when i select mod folder to "My Documents" it uses the onedrive documents path instead of the system documents folder.

I dont want to use onedrive, how can i fix this?

<img width="353" alt="image" src="https://user-images.githubusercontent.com/74363821/221105297-b15a43e5-3b65-45c0-9b23-7b64332cd6b0.png">

### Attachments

[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/10821135/output_log.txt)
[MSCLoader_Preloader.txt](https://github.com/piotrulos/MSCModLoader/files/10821136/MSCLoader_Preloader.txt)

**Comment by piotrulos** [comment]
You need to disable replacing documents in OneDrive, or select different folder.   

OneDrive replaces documents as default path, you either need to disable it or choose different folder as mods folder.
