### ISSUE TITLE
[Bug]: (API) OnModEnabled and OnModDisabled behaviour

### ISSUE THREAD

**Issue by Strikeless** [piotrulos/MSCModLoader#166]
### OS version/build

Windows 10 22H2 19045.2728

### MSCLoader version

1.2.11 build 285

### Description

Problem:
The OnModEnabled and OnModDisabled setup functions do not get called upon game/MSCLoader startup or game/MSCLoader closing.

Expected behaviour:
The OnModEnabled function would also be called when the mod is initially enabled by MSCLoader (upon game starting), and the OnModDisabled function would also be called when the mod is disabled by MSCLoader upon game closing.

Additional notes:
If this is intended behaviour, it could be wise to add a note about this to the summaries of the Setup enum values.
As expected, the functions do get called when the mod is manually enabled or disabled through the installed mods UI.

### Attachments

Not applicable to type of issue.

**Comment by piotrulos** [comment]
This always was for only manual disable/enable. The "Expected behaviour:" makes 0 sense, never seen loader with that "behaviour".
