### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by zegreatclan** [piotrulos/MSCModLoader#17]
I understand that you're not responsible of what happens in game :D , but maybe you could answer me,

I make a "dashboard" software, and I would have been interested by getting speed and RPM, but it looks like the data is not available as I would have hoped for, I've tried the speed using these ones :

[FsmFloat] SpeedKMH
[FsmFloat] SpeedValmet

Speed Valmet seems to work in Valmet :D good point, but i could not find any property suitable for the van for instance,

Is there an universal property for speed, rpm and max rpm ? Or is it worthless trying ?
Obviously all the data I already got using your plugin is already a lot,

Thanks for your efforts !

Nicolas

**Comment by piotrulos** [comment]
It is possible, but not by playmaker variables. 
You can get these variables (speed, rpm, gear, etc..) from `Drivetrain` class. (you need to add `Assembly-CSharp.dll` reference).  

Here small example:  
```
GameObject satsuma = GameObject.Find("SATSUMA(557kg)");
satsuma.GetComponent<Drivetrain>().rpm;
satsuma.GetComponent<Drivetrain>().differentialSpeed;
(and more like this)
```

**Comment by zegreatclan** [comment]
Cool ! 

I think i've got it, I admit with the help of the FindMyCar plugin code :D

Last question and I stop bullying you,

I've properly installed everything unity etc ..., but I can't debug the plugin with visual studio, 
Is there a trick to get the debugger property attached to the plugin ? Currently I can attach, but there is no breakpoint hits, I admit the unity framework is brand new for me :D

**Comment by piotrulos** [comment]
Actuallly there is no way to attach debugger. I was thinking about debugger but it need more work.

The best way for now is to print values in-game, to `ModConsole.Print()`, or use `try {} catch(Exception e) {}` (also print exception `e.Message` to console) to track errors.

**Comment by zegreatclan** [comment]
Thanks for the response ;) Obviously it gives even more value to your loader, creating it without debugger is even more hard ;)

I will stick to my text file output for exploring properties :D 

Thanks again !
