### ISSUE TITLE
An error with MSC Loader

### ISSUE THREAD

**Issue by gitabci31** [piotrulos/MSCModLoader#173]
### OS version/build

Windows 10

### MSCLoader version

1.2.13

### Description

I enter the game normally. I get this error when I continue the game after saving the game. When I uninstall MSC Loader, the problem goes away, but I want to play my game with mods. I don't know if it is due to MSC Loader or a mod. When I look at the error log, I can't find any clue as to why I'm getting a crash. 

### Attachments

![image](https://github.com/piotrulos/MSCModLoader/assets/140354416/a3479a8d-b45d-4713-9699-f99d17e1316f)

**Comment by piotrulos** [comment]
[No log = invalid]

Most likely it's caused by one of the mods, try without mods, if it doesn't happen if you disable mods, then it's one of the mods issue.
