### ISSUE TITLE
[Bug]:PRELOADER CRASH 

### ISSUE THREAD

**Issue by govnap** [piotrulos/MSCModLoader#175]
### OS version/build

win 10 x64 22h2

### MSCLoader version

1.2.13

### Description

mscloader is not starting

### Attachments

[MSCLoader_Preloader.txt](https://github.com/piotrulos/MSCModLoader/files/12402819/MSCLoader_Preloader.txt)
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/12402820/output_log.txt)

**Comment by piotrulos** [comment]
Try clean install, run patcher and click "remove mscloader" first, and then do "install mscloader"

**Comment by govnap** [comment]
i've done it before

**Comment by govnap** [comment]
I've done it before

**Comment by piotrulos** [comment]
So you probably using modified/pirated game
