### ISSUE TITLE
[Bug]: Error with running mscloader also says msc.features

### ISSUE THREAD

**Issue by PatrickStar178** [piotrulos/MSCModLoader#176]
### OS version/build

Edition	Windows 11 Home Version	22H2 Installed on	‎8/‎22/‎2023 OS build	22621.2134 Experience	Windows Feature Experience Pack 1000.22659.1000.0

### MSCLoader version

Latest 1.23 

### Description

The bug I'm experiencing is it keeps crashing the game everytime I load the game it tries to say something about mscloader.features but closes before I can even get to click on it to open the website up, it also says something about compability but I should have all the things, so I'm not for sure what's going on, it makes it worse because I had to reset my pc the other day and then when I tried redownloading mscloader it installed sucesfully but it kept saying that about the msc.features.

### Attachments

[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/12425937/output_log.txt)
[MSCLoader_Preloader.txt](https://github.com/piotrulos/MSCModLoader/files/12425938/MSCLoader_Preloader.txt)

**Comment by piotrulos** [comment]
Semms like you mising lots of files.
- Verify game files on steam, so it will download missing files,
- Redownload and reinstall mods that errors out (mostly mop since you have wrong version of it)
- Click "yes" on every prompt when asked to download references.

**Comment by PatrickStar178** [comment]
thank you so much!! I think it worked
