### ISSUE TITLE
(Linux native version) Included plugins make the game crash  [Bug]: 

### ISSUE THREAD

**Issue by Pablotheexplosionfemboy** [piotrulos/MSCModLoader#177]
### OS version/build

Arch Linux x86_64  (kernel 6.4.12-arch1-1)

### MSCLoader version

1.2.13

### Description

Upon installing the native linux version of MSC (included in MSC loader linux experimental) the game crashes. Doesn't matter if I run the game under Proton, MSC (Native) or MSC + MSCLoader (Native)
upon some basic troubleshooting, I found that the source of the problem is caused by all the included x86_64 plugins, as the game launches normally without them (ofc not native tho)

This was done on a fresh installation of MSC and with no mods.

Also, I'm not sure whether to put this in the Proton discussion, as it isn't technically under Proton? So I apologize if I should have put it there.

### Attachments

[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/12484506/output_log.txt)

[MSCLoader_Preloader.txt](https://github.com/piotrulos/MSCModLoader/files/12484527/MSCLoader_Preloader.txt)

**Comment by Pablotheexplosionfemboy** [comment]
Shortly after this, I found  #164 and tried to use the libdoorstop.co fix, but it did not work.

**Comment by piotrulos** [comment]
Currently it's a thing that I can't reproduce.
