### ISSUE TITLE
[Bug]: My loader can't load all of my mods, only some

### ISSUE THREAD

**Issue by thatonean** [piotrulos/MSCModLoader#179]
### OS version/build

Windows 10 Pro Build 19045

### MSCLoader version

1.2.13

### Description

My mods aren't all loaded, somehow only one that i seen loaded fully

### Attachments

[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/12558594/output_log.txt)
[MSCLoader_Preloader.txt](https://github.com/piotrulos/MSCModLoader/files/12558595/MSCLoader_Preloader.txt)

**Comment by piotrulos** [comment]
As description and faq says don't use cloud storage (like onedrive) as mods folder
