### ISSUE TITLE
Cars fuck'd up when installed MSCModLoader

### ISSUE THREAD

**Issue by Kusimulkku** [piotrulos/MSCModLoader#18]
Hello, after i installed the MSCModLoader the cars started to bug, after i start the engine, the car starts flippping over the world.. if you want, i can film a video about it.

**Comment by piotrulos** [comment]
99% mod problem not modloader.

**Comment by Kusimulkku** [comment]
I have no mods in the ''Mod'' folder, just the patcher installed.

**Comment by Kusimulkku** [comment]
I have no mods in the ''Mod'' folder, just the modloader installed.
