### ISSUE TITLE
[Bug]:  Templates, both 2019 and 2022 will not work

### ISSUE THREAD

**Issue by r212ro** [piotrulos/MSCModLoader#183]
### OS version/build

Windows 10 Pro 22H2 19045.3570

### MSCLoader version

1.12

### Description

I downloaded Visual Studio according to the guide, but when I installed the templates and double clicked them, and neither of them worked.

### Attachments

![mod](https://github.com/piotrulos/MSCModLoader/assets/145169960/7bbc0aff-73ca-4358-baad-b296822ee57c)
[mod.txt](https://github.com/piotrulos/MSCModLoader/files/13329978/mod.txt)

**Comment by piotrulos** [comment]
VS 2017 is not supported anymore. You need to install 2019 or 2022
