### ISSUE TITLE
[Bug]: MSCLoader Failing to get update information

### ISSUE THREAD

**Issue by Voltag20** [piotrulos/MSCModLoader#186]
### OS version/build

Version	10.0.19045 Build 19045

### MSCLoader version

1.2.14

### Description

The Loader is unable to access the remote sever I've allowed steam and the game itself to access the fire wall I don't have any antivirus that's stopping it. I've seen someone ask about this before and the response was something to do with the users internet connection, but I've tried everything, I've uninstalled and reinstalled everything.

Will the mod still run fine with these errors I've been looking everywhere for something that I've missed and I have no idea

### Attachments

[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/13694225/output_log.txt)
[MSCLoader_Preloader.txt](https://github.com/piotrulos/MSCModLoader/files/13694228/MSCLoader_Preloader.txt)
![Untitled](https://github.com/piotrulos/MSCModLoader/assets/154028051/4077ef76-1d58-4d0e-819a-3a066c017521)

**Comment by piotrulos** [comment]
Can you access version info directly? [By clicking here](http://my-summer-car.ovh/ver.php?core=stable)

**Comment by Voltag20** [comment]
I just clicked the link and its saying the connection timed out

**Comment by piotrulos** [comment]
So something is wrong with your internet.

**Comment by Voltag20** [comment]
any ideas on where to look?

**Comment by piotrulos** [comment]
Check your dns settings, or whatever firewal, av you are using.

**Comment by Voltag20** [comment]
changed my DNS settings to google 8.8.8.8 and turned off my firewall fully to check to see if thats the problem and its still not going to the website.

**Comment by Voltag20** [comment]
hmmm yea your right i don't know what is up with my network i've tried everything yet my phone data can access it just fine i'm really confused
