### ISSUE TITLE
[Bug]: Not Letting Me Close MSC Loader Or Save Mod Settings.

### ISSUE THREAD

**Issue by EENexusMods** [piotrulos/MSCModLoader#197]
### OS version/build

Windows 11 Home

### MSCLoader version

v1.2.14

### Description

**None Of My Mod Settings Are Saving.
My Console Isnt Closing**

### Attachments

[output_log.txt](https://github.com/user-attachments/files/17032349/output_log.txt)
[MSCLoader_Preloader.txt](https://github.com/user-attachments/files/17032351/MSCLoader_Preloader.txt)
![Screenshot 2024-09-17 175140](https://github.com/user-attachments/assets/4066e50b-bab2-4b64-8481-591564e18304)

**Comment by piotrulos** [comment]
Try reinstailing mscloader, open installer and then click "remove mscloader" and after that click "install mscloader". If that doesn't fix the issue then just delete entire "Config" folder that is inside your Mods folder

**Comment by EENexusMods** [comment]
> Try reinstailing mscloader, open installer and then click "remove mscloader" and after that click "install mscloader". If that doesn't fix the issue then just delete entire "Config" folder that is inside your Mods folder

Thanks It Worked!
