### ISSUE TITLE
Some mods break in 0.2

### ISSUE THREAD

**Issue by haverdaden** [piotrulos/MSCModLoader#2]
Hey I'm a developer for some of the mods in Msc like GrabAnything, Noclip, Godmode etc. 
These mods work well in 0.1 but won't run with the 0.2 modloader. 

I'm not quite sure what i causing this as this modloader only produces 1 error that is object reference not set to an instance of an object. This error won't be produced in the 0.1 modloader.

I can only think of one reason that could be a problem. I'm using Unity gui for all my mods.

**Comment by piotrulos** [comment]
Can confirm with your Noclip mod. 
Did you try to recomple this mod? Remember to add new MSCLoader.dll reference in your project, not the old one.

According to Debug info, this error is thrown somewhere in your OnLoad() function, maybe you try to load object that doesn't yet exists, or something like that?

I need to add more debugging features in next update.

**Comment by haverdaden** [comment]
I think I found the problem for the Noclip mod atleast. I had a Gameobject.Find in there that was trying to find a not yet existing gameobject. i guess 0.1 modloader was loading slower. I've fixed it now. 

It's not a bug with the modloader then. You can close this.

**Comment by piotrulos** [comment]
Thanks for the info, where problem was.

I will add more debug info in error messages for modders in next small update. (0.2.2)
