### ISSUE TITLE
[Bug]: The game freezes and loads endlessly. Support in Russia?

### ISSUE THREAD

**Issue by RuslandUser** [piotrulos/MSCModLoader#201]
### OS version/build

Windows 10 1909 (18363.1556)

### MSCLoader version

1.2.14

### Description

Initially, the game completely freezes at a certain point in time, when rebooting with a save, everything repeated (at the same moment).  After starting a new game, everything worked for some time, after which it happened again. When saving the game before the dependency, the loading became endless.

The game is licensed and works without a launcher. Auto-updates do not work, nor does the connection with steam (SteamAPI failed with error: Error getting response stream (ReadDone1): ReceiveFailure)

### Attachments

[output_log.txt](https://github.com/user-attachments/files/17175956/output_log.txt)

[MSCLoader_Preloader.txt](https://github.com/user-attachments/files/17175960/MSCLoader_Preloader.txt)

**Comment by piotrulos** [comment]
That's not a bug, something blocking update checking on your side
