### ISSUE TITLE
[Bug]: hi hello might be a bug or something

### ISSUE THREAD

**Issue by sotkat34** [piotrulos/MSCModLoader#208]
### OS version/build

I think its just windows 10, sorry I really don't know

### MSCLoader version

the newest one, downloaded from nexus mods TODAY

### Description

so pretty much if I download it form nexus then extract it to the mods folder before it wont do shit, as in changelog will be normal not the correct one and all that, and its not my pc either I don't think because I reinstalled the game because I had some incorrect mods so wanted a fresh start and all that but back then it was showing up but not anymore for some reason

### Attachments

   
![My Summer Car Screenshot 2024 10 28 - 17 55 10 01](https://github.com/user-attachments/assets/6943b903-e9fc-4669-9ce6-4f6ec415bd11)

couldn't find the asked for file but here's some pictures and shit, 
![Capture](https://github.com/user-attachments/assets/863d65e0-9cde-4cfb-b327-43fe99884415)
changed resolution down so it saves as a screenshot that can actually be seen

**Comment by piotrulos** [comment]
Read manual again.
