### ISSUE TITLE
AssetBundle.CreateFromMemoryImmediate null when reloading save

### ISSUE THREAD

**Issue by UltraJohn** [piotrulos/MSCModLoader#21]
bundle = AssetBundle.CreateFromMemoryImmediate(File.ReadAllBytes(path));

The first time you load your save the assets loads just fine, but if you quit and hit continue again, it will return null the second time. Not sure how I can fix this, maybe it's a bug?

**Comment by piotrulos** [comment]
Make sure you unload bundle after get everything you need. (at the end of function/coroutine)

`bundle.Unload(false);`

**Comment by UltraJohn** [comment]
That fixed it! Thanks!
