### ISSUE TITLE
[Bug]: My FPS dropped so badly

### ISSUE THREAD

**Issue by NZ-45** [piotrulos/MSCModLoader#213]
### OS version/build

Windows 11 Pro (22631.4391)

### MSCLoader version

1.2.14 Build 299

### Description

Whenever i loaded into the game, then facing my POV to Satsuma, my framerate drop slowly by 1% until 9 FPS (below 20 fps) every 2 or 5 minutes.
Then i checked everything from the Command and seems perfectly fine but my framerate mysteriously dropped (well, i don't know how to check what seem to be the problem) *Forgive my bad English 

My PC specs :
Intel i7 8th gen 6 core, 12 threats
32gb Ram
Nvidia Quadro P1000 4gb Vram

And here's the outputlog if you interested.. 
but still, i need help..

### Attachments

[output_log.txt](https://github.com/user-attachments/files/17619903/output_log.txt)

**Comment by piotrulos** [comment]
I'm not developer of the game, this is mscloader and you don't even have mscloader installed
