### ISSUE TITLE
[Bug]: Method not found: 'MSCLoader.Settings.Get' (updated 1.2.14 -> 1.3)

### ISSUE THREAD

**Issue by akzar-dev** [piotrulos/MSCModLoader#217]
### OS version/build

Windows 11 Pro 23H2

### MSCLoader version

1.3

### Description

Hello there!

Fist of all, thank you for keeping MSCLoader alive and updated.

I've got an issue after updating from 1.2.14 to 1.3 (important note - I updated via the installer, as recommended in the patch notes) - one of my mods (Display Bolt Sizes, [this one](https://www.nexusmods.com/mysummercar/mods/2235)) started throwing an error:
```
MSCLoader ERROR: Mod DisplayBoltSize has thrown an error!
Details: Method not found: 'MSCLoader.Settings.Get'. in Void ModSettingsLoaded()
System.MissingMethodException: Method not found: 'MSCLoader.Settings.Get'.
  at DisplayBoltSize.DisplayBoltSize.ModSettingsLoaded () [0x00000] in <filename unknown>:0 
  at MSCLoader.ModMenu.LoadSettings () [0x00000] in <filename unknown>:0 
```

Nothing changed except the MSCLoader version. On first start after update it updated *Pro* compatibility resources, and that's it.
That the mod in question that's giving the error seems to work ok, just for some reason throws that in the log.

Last but not the least - removing/installing MSCLoader didn't help.

Thank you!

### Attachments

[output_log.txt](https://github.com/user-attachments/files/18194261/output_log.txt)
[MSCLoader_Preloader.txt](https://github.com/user-attachments/files/18194262/MSCLoader_Preloader.txt)

**Comment by piotrulos** [comment]
Did someone really used undocumented internal variable to read settings data? Technically unfixable, because that no longer exists

**Comment by piotrulos** [comment]
I might actually found a dirty fix for this, it should work in build 341 now

**Comment by akzar-dev** [comment]
It does work in 341, thank you!
Checked out your changes, good stuff, thank you for restoring that *undocumented crap*, idk why mod uses it 🤷
