### ISSUE TITLE
[Bug]: Using ModAudio.Play() with specified time does not work

### ISSUE THREAD

**Issue by dadly25** [piotrulos/MSCModLoader#219]
### OS version/build

Windows 10 22H2

### MSCLoader version

1.3

### Description

Hi, when using `ModAudio.Play()` with a time float, the method simply does not work and the audio does not play.
Example code:
`audioPlayer.audioSource = audioSource;`
`audioPlayer.LoadAudioFromFile(file, true, true);`
`float time = 82.73;`
`audioPlayer.Play(time, 1f);`

I may just be stupid and doing something wrong but for the life of me I cannot figure out why this doesn't work.
Simply using `audioPlayer.Play()` without specifying time works perfectly fine.

### Attachments

[output_log.txt](https://github.com/user-attachments/files/18219702/output_log.txt)
[MSCLoader_Preloader.txt](https://github.com/user-attachments/files/18219703/MSCLoader_Preloader.txt)

**Comment by dadly25** [comment]
By the way, I am using VS 2022 and the issue was happening in the previous MSCLoader version as well.

**Comment by piotrulos** [comment]
Make sure the time you specify isn't bigger than your clip.lenght

**Comment by dadly25** [comment]
Assuming that `time` means seconds from start then the file is long enough. no matter what value I try to use the result is always the same, the only difference is when I don't use it in which case it's fine.

**Comment by piotrulos** [comment]
maybe you use file that don't support seeking?

**Comment by dadly25** [comment]
Same result with .ogg .flv and .mp3

**Comment by dadly25** [comment]
I enabled `log-all mods true` and this is part of the output when trying to use `.Play(time)`
![image](https://github.com/user-attachments/assets/4042288f-f7f0-4e71-ae05-79dd7e324548)

**Comment by piotrulos** [comment]
Coroutines needs to be part of monobehaviour attached to gameobject. If you never attached mb it will fail to execute.

**Comment by dadly25** [comment]
> Coroutines needs to be part of monobehaviour attached to gameobject. If you never attached mb it will fail to execute.

Instead of doing `ModAudio audioPlayer = new ModAudio();` I changed it to:
`ModAudio audioPlayer;`
`playerObject.AddComponent<ModAudio>();`
`audioPlayer = playerObject.GetComponent<ModAudio>();`

Doing this fixed the issue of not playing audio at all and got rid of the error message as well, but it still refuses to play from specified time and just plays from the beginning of the file.

**Comment by dadly25** [comment]
Setting `doStream` as false in `LoadAudioFromFile();` seems to have largely fixed the issue, although there's still a weird distortion when using .ogg specifically

**Comment by piotrulos** [comment]
ModAudio is monobehaviour so you can't use "new ModAudio();" since monobehaviours cannot be instanced from constructor.
