### ISSUE TITLE
Adding a custom UI element to top left

### ISSUE THREAD

**Issue by UltraJohn** [piotrulos/MSCModLoader#22]
I'm currently making a mod and I want to add a new text element to the top left below the money text. However after spending quite a while positioning my custom text properly, I realize that changing resolution/aspect ratio changes the location and size of the money text, which means my text is no longer in the right position. Would it be possible to get a method that can add a new element automatically? Or perhaps if you know of a way to get the position of the money text and just offset my text below that. This is all I have left to do before I can release my mod :(

**Comment by piotrulos** [comment]
This UI is some playmaker shit, I never touch this ui (everything I use is UnityEngine.UI) But as far as I know this is some kind of GameObject. You should search for this gameobject and attach your own object to parent.

Write simple test mod and dump all gameobject names to file, something like this:
```
using(StreamWriter writer = new StreamWriter("gameobjects.txt", true))
{
   foreach (GameObject obj in Object.FindObjectsOfType<GameObject>())
   {
       writer.WriteLine(obj.name);
   }
}
```

I think the next thing to do should be mod friendly hud ui;

**Comment by UltraJohn** [comment]
Yeah i tried that, I got a list of 3000 objects, no idea which one it is though, if it even is any of them. There is one called GUI but It doesn't seem to have any variables related to text elements. Do you think it's possible to raycast the ui and get the position data? I tried but got nothing, though I'm not that good with unity so maybe I'm just doing it wrong... I have attached the dump file which your code generated, in case you wanna take a look at it. After several hours I'm kinda out of ideas on what to do.
[gameobjects.txt](https://github.com/piotrulos/MSCModLoader/files/1369569/gameobjects.txt)

**Comment by piotrulos** [comment]
It looks like this is GUI gameobject
I dump child gameobjects of this GUI and there is something called HUD
[GUI childs.txt](https://github.com/piotrulos/MSCModLoader/files/1369644/GUI.childs.txt)
That's may be it.

**Comment by UltraJohn** [comment]
Can you paste me the code to get that?

**Comment by piotrulos** [comment]
HUD = PlayMakerFSM 
That's what i thought,  
But at least here is gameobject, just transform your gameobject with text to parent of HUD and this should work.

```
 GameObject obj = GameObject.Find("GUI");
foreach (Transform go in obj.GetComponentsInChildren<Transform>())
{
     if(go.name == "HUD")
     {
         yourgameobject.transform.SetParent(go.transform, false);
     }
}
```

**Comment by piotrulos** [comment]
OK I found how to do this
Here is a code:
```
//Find Hud
GameObject hud = GameObject.Find("GUI/HUD");

//Clone money display
money = GameObject.Instantiate(GameObject.Find("GUI/HUD/Money"));

GameObject money_text = money.transform.Find("Text").gameObject;
GameObject money_bg = money.transform.Find("BarBG").gameObject;
GameObject money_data = money.transform.Find("Data").gameObject;
                
//Rename GameObject name to remove (clone) text
money.name = "Something"; //New parent name instead of Money

//change parent
money.transform.SetParent(hud.transform, false);

//Destroy PlayMaker in Data (to change value)
Object.Destroy(money_data.GetComponent("PlayMakerFSM"));

//change text
money_text.GetComponent<TextMesh>().text = "Name";
money_data.GetComponent<TextMesh>().text = "Value";

money.transform.localPosition -= new Vector3(0, 0.5f); //Move a little down
```

And it will look like this
![hud](https://user-images.githubusercontent.com/4009096/31385295-0e86d52c-adc3-11e7-8a9a-b943da27016a.png)

**Comment by UltraJohn** [comment]
You are a genius, that solved it! Thanks man!
