### ISSUE TITLE
[Bug]: Modloader stuck in phase 2

### ISSUE THREAD

**Issue by 007AgentRL** [piotrulos/MSCModLoader#220]
### OS version/build

Windows 11 23H2     22631.4602

### MSCLoader version

1.3

### Description

The Mod loading Process is getting stuck in phase 2 when running the game, i tried deactivating the mods that its getting stuck on and it chooses the next mod in the folder and does the same. The console shows that its loading all the mods and also gets stuck on the mods that are in that position where it always gets stuck. It doesnt matter what mod it is, it does the same. 

### Attachments

[MSCLoader_Preloader.txt](https://github.com/user-attachments/files/18252366/MSCLoader_Preloader.txt)
[output_log.txt](https://github.com/user-attachments/files/18252367/output_log.txt)
![image](https://github.com/user-attachments/assets/5219731b-ddaf-464c-b0a9-1bb940109d28)

**Comment by piotrulos** [comment]
You can try deleting entire "Config" folder that is in Mods folder. If that doesn't help verify game files on steam and use option "reinstall mscloader" from the installer. There are some weird errrors that your game throws.

**Comment by 007AgentRL** [comment]
> You can try deleting entire "Config" folder that is in Mods folder. If that doesn't help verify game files on steam and use option "reinstall mscloader" from the installer. There are some weird errrors that your game throws.

Worked! Thanks!!
