### ISSUE TITLE
Console Says Steam Not Found

### ISSUE THREAD

**Issue by XxDeathStalkerxX325** [piotrulos/MSCModLoader#25]
In  MSC Beta it'll say Steam Version not supported only works for steam version. Is it because I'm on Beta? I bought the game from steam so what's up?

**Comment by piotrulos** [comment]
This error shouldn't happen when you run it via steam (not via exe)

Also there may be something broken in beta branch, but I focus mainly on stable branch, so there will be no fix until beta will be in stable branch (but I track changes and it appears that nothing is broken i beta)

**Comment by XxDeathStalkerxX325** [comment]
Okay it may be because I launched via exe
