### ISSUE TITLE
Disabling plugins not work

### ISSUE THREAD

**Issue by GishaSeven** [piotrulos/MSCModLoader#26]
In main menu I press ctrl + m, select plugin(Lower Satsuma) and click on checkbox, then I press again ctrl + m for close plugins list and again open plugins list and can see, that needed plugin is disabled. But then I load my save and plugin not disabled.

**Comment by piotrulos** [comment]
Can't reproduce.
Tested it now and plugin stays disabled when in game.

**Comment by piotrulos** [comment]
I actually found problem, some mod creators use Update to load mods instead of OnLoad, this will be fixed in next update.
