### ISSUE TITLE
Documentation missing link

### ISSUE THREAD

**Issue by UltraJohn** [piotrulos/MSCModLoader#27]
https://github.com/piotrulos/MSCModLoader/wiki
Missing hyperlink for "How to create and use Asset Bundles"

**Comment by piotrulos** [comment]
I know, I just started writing this guide and didn't finish it. It will be active when I finish this guide.
Most likely there will be download for unity project with asset bundle script (to generate *.unity3d files)

**Comment by UltraJohn** [comment]
Ah ok sounds good
