### ISSUE TITLE
Keybind bug

### ISSUE THREAD

**Issue by jontamasan** [piotrulos/MSCModLoader#29]
I seems that I found bug at [Keybind.cs](https://github.com/piotrulos/MSCModLoader/blob/master/MSCLoader/MSCLoader/Keybind.cs)

ver0.3.2
```
public bool IsPressed()
{
	if (Modifier != KeyCode.None)
	{
		return Input.GetKey(Modifier) && Input.GetKey(Key);
	}
	return Input.GetKeyDown(Key);
}
```
When Keybind.Modifier is NOT set, It will not be hold down.
I think the following is correct at last line.
`return Input.GetKey(Key);`
Is this correct?

**Comment by piotrulos** [comment]
It's ok, KeyCode.None is empty key, and here is "if modifier not empty", so modifier is present.

**Comment by jontamasan** [comment]
Thank you for reply.
But what I mean, if just modifier is empty (only one key binding ).
In this case, it will behave same as Keybind.IsDown(), isn't it?.

**Comment by piotrulos** [comment]
That is in second return when modifier is none  `return Input.GetKeyDown(Key);` 
First return is when modifier is present `return Input.GetKey(Modifier) && Input.GetKey(Key);` need to hold both keys

**Comment by piotrulos** [comment]
Oh I see what you mean now, When there is no modifier is simple press not hold. 
This code is untouched from 0.1, so it's not mine code.
I see that no one is using this, and there is no indication in settings to hold keys. 
So most likely this function need to be removed.

**Comment by jontamasan** [comment]
Yes! Thanks for noticing.
But I am trying to use it with MOD I'm making now.

**Comment by piotrulos** [comment]
I will fix that, but what's the point of holding key? Most of mods use keybinds to open menu, activate feature or something like that.
Holding is good for driving car, walking etc.

**Comment by jontamasan** [comment]
hehe... Holding key & mouse moving, then item rotation. How is it?

**Comment by piotrulos** [comment]
You can use in-game features. If you want grab object, rotate with mouse etc. (like this is in game) just put object on "Parts" Layer. `LayerMask.NameToLayer("Parts");`
You can also use in-game keybinds from `cInput.dll`

If you are not duplicate any in-game features/keybinds then you can create your own keybind.

**Comment by jontamasan** [comment]
Wow many many thanks! I try it.

**Comment by Nerezza** [comment]
Backpack mod is having trouble with the hotkey to open its inventory ever since this change. Pressing tab to open the inventory will rapidly open/close the inventory fast enough that long taps can open/close multiple times, and brief taps will open/close the inventory once. Only the briefest of taps on the hotkey will open its inventory without closing it again.
