### ISSUE TITLE
Suspensão do Satsuma 

### ISSUE THREAD

**Issue by daniloantunees** [piotrulos/MSCModLoader#30]
Olá!

Com a nova atualização 24/10, a suspensão do satsuma não altera. Teria como verificar?
Já uso a versão 3.3 do MSCLoader.

Obrigado!

Danilo Antunes
Brasil

**Comment by daniloantunees** [comment]
Hello!

With the new update 24/10, the suspension of satsuma does not change. Would you like to check?
I already use version 3.3 of MSCLoader.

Thank you!

Danilo Antunes
Brazil

**Comment by piotrulos** [comment]
Update your mods, this is not related to MSCLoader.
