### ISSUE TITLE
Long delay when ModLoader can't reach Host Computer

### ISSUE THREAD

**Issue by Shazuli** [piotrulos/MSCModLoader#31]
***Hi!***

I'm doing quite a bit of modding with your templates and ModLoader. So it's a lot of closing and opening of the game. That is fine but the problem I'm having is that in certain occasions when launching the game my computer has a problem of reaching the host computer that keeps track of new updates, so instead of letting me progress the game freezes for about 8-10 seconds. After the game comes back it will not show whenever or not this is the latest version or if there is a new update as well as typing a error message in the console (the amount of times this can happen is from every 1/3 to every time I launch the game).
As you can understand this is very frustrating when you have to restart the game a lot if you have to wait 10 seconds every time for the game to load.
My suggestion is a new variable in the configs that if it's `false` should **not** look for any new updates (it would be set as `true` as default of course).

(This picture shows the error message in the console. It is in Swedish but it basically says it couldn't find the host computer in time)
![mscmodloader error](https://user-images.githubusercontent.com/9884180/32691813-b82ba7a2-c70d-11e7-8416-1efd473ef2ab.png)

**Comment by piotrulos** [comment]
No plan for this feature until mod settings will be implemented.

As a workaround there is a dev flag in MSCLoader, so if you want you can compile yourself latest version of MSCLoader from source https://github.com/piotrulos/MSCModLoader/tree/v0.3.3
under `ModLoader.cs` change `static bool experimental = false;` to `static bool experimental = true;` compile and move compiled `MSCLoader.dll` to `Steam\steamapps\common\My Summer Car\mysummercar_Data\Managed` and replace.

**Comment by Shazuli** [comment]
Eh, umm... I got some problems when trying to compile it:

![mscmodloader compile problems1](https://user-images.githubusercontent.com/9884180/32692841-a5e3c2c0-c71f-11e7-878f-570bf4283a3f.png)


![mscmodloader compile problems2](https://user-images.githubusercontent.com/9884180/32692802-223e0e1c-c71f-11e7-9e12-56726fc49902.png)

You have to excuse my incompetent, I'm not used to this kind of programming when using custom libraries and `.dll` files (and Visual Studio for that matter).

**Comment by piotrulos** [comment]
Add references from `Steam\steamapps\common\My Summer Car\mysummercar_Data\Managed`
```
Assembly-CSharp-firstpass.dll
UnityEngine.dll
UnityEngine.UI.dll
PlayMaker.dll
```
This should compile. Click `Build > Build Solution` and you will find `MSCLoader.dll` in `MSCLoader\MSCLoader\bin\Release`

**Comment by Shazuli** [comment]
Thank you sir! Now I can keep all my hair on my head now that I don't have to wait 10, long, painful, seconds every time I recompile!
