### ISSUE TITLE
Event listener

### ISSUE THREAD

**Issue by JohnHestehave** [piotrulos/MSCModLoader#32]
Is there a way to register a function to run when the player dies? In the list of variables and events there is "DEATH", but how do you use it to call a function on death? Or maybe there is an easier way to know if the player dies?

**Comment by piotrulos** [comment]
I never found a way to "do something when playmaker event happen". 

You should search through Player gameobject, maybe there is a variable isdead or something like that.

**Comment by JohnHestehave** [comment]
Couldn't find anything like that using DeveloperToolset mod. But I found that the player has a CharacterMotor script or something that gets removed when you die. Maybe if i just check if the variable is null it means you are dead? Not sure if this is a good solution, do you think this would work?

**Comment by JohnHestehave** [comment]
Ok I think it might be working :D I'm gonna use this method and hope it doesn't cause any unwanted behavior lol
