### ISSUE TITLE
Getting bolt size?

### ISSUE THREAD

**Issue by Zyles** [piotrulos/MSCModLoader#34]
Where is the playmaker code stored? I tried to de-assemble the game but could not find it.

What I want to do is a simple mod, when you look at a bolt it should display the size on the tooltip.

I couldn't find a variable for the bolt size in your list.

Any easy way of doing this?

**Comment by piotrulos** [comment]
Playmaker has no code, it is "graph language", everything related to playmaker is in GameObjects (except for global variables which is on my list)

You need to dig through  gameobjects and find specific playmaker for bolts, and then access it through code using GetComponent. Use developer toolkit mod, this mod will help you with that.

**Comment by Zyles** [comment]
Okay will take a look at it. Thanks.

Playmaker is cancer for modding...

**Comment by Zyles** [comment]
I used the dev toolkit, and found a variable called BoltSize, but it is ALWAYS zero. On every screw I look at.

Any clues?

**Comment by piotrulos** [comment]
I know, playmaker sucks for modders.

Maybe it shows only when attached or deattached? Or maybe wrong gameobject, as far as I know the name is boltPM or something like that. Check all parent or child objects.

**Comment by Zyles** [comment]
I attached a main bearing to the crankshaft for example, then the bolt is visible and I raycast on it to get the data. There is a boltPM and a screw gameobject, but it says BoltSize 0, and I can't find any other data regarding boltsizes.

Only data on how tight it is screwed, if it is on or off.

So I have no idea how to get this info sadly...
