### ISSUE TITLE
Use System.IO.Path.DirectorySeparatorChar

### ISSUE THREAD

**Issue by RedKugelblitz** [piotrulos/MSCModLoader#35]
trivial little fix, should improve portability. I'm trying to run the Patcher on linux and it doesn't work just because of the backslash/forward slash problem

**Comment by piotrulos** [comment]
It's not designed for linux, and all mods will need to change that, not only patcher.
So it's useless.

**Comment by piotrulos** [comment]
Waste of time for 0.27% steam users.
Nobody will fix their mods for few users.

**Comment by RedKugelblitz** [comment]
The unity player is platform agnostic, so it should be worth a shot, at least
Also take a look at the pull request associated with the issue

**Comment by RedKugelblitz** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=142372419
A commenter in this thread got mods working with an older version of MSCLoader
