### ISSUE TITLE
It won't work any more

### ISSUE THREAD

**Issue by Gnagtsa** [piotrulos/MSCModLoader#38]
Well I know that piotrulos is not gonna answer because he thinks I am hating right now so please answer me. So I have modloader for a pretty long time and had very much fun with mods. Thanks to piotrulos. But suddenly after the update 0.3.5 I can't play with my mods any more. I have them in the modfolder and it still doesn't work. Please answer piotrulos. He'll probably won't care so why am I writing this.

**Comment by piotrulos** [comment]
How can I help you with these useless information you provide?
Any errors? any logs? what doesn't work? did you try repatch?

**Comment by RedKugelblitz** [comment]
Ok, as piotrulos said, we need more info. If you could open the console *before* continuing the game (still on the main menu) and tell us what appears on the console, it'll be easier for us to help you

**Comment by Gnagtsa** [comment]
Well. I've reinstalled it 2 times and the patcher works. Everything is normal until I get ingame and then press control+m to see wich mods are active. All mods are in the mod folder and still there aren't any mods active msc loader is up to date everything is fine but it still doesn't work. Thanks for replying.

**Comment by piotrulos** [comment]
I can only guess, one of your mods is broken.

**Comment by Gnagtsa** [comment]
can't be i've reinstalled them to

**Comment by RedKugelblitz** [comment]
He meant the mod itself must be broken from download. See if other mods present the same problem. If not, contact the mod author describing the situation, otherwise the loader is broken

**Comment by piotrulos** [comment]
You should try clean install of MSCLoader.
Remove everything from game "Managed" folder, run game files integrity check on steam, After this use patcher again. Sometimes files may be corrupted or something.

**Comment by Gnagtsa** [comment]
Well still doesn't work. Anyways thank you I will just enjoy this game without mods.
