### ISSUE TITLE
Checking if exists in assets folder

### ISSUE THREAD

**Issue by Fredrik95** [piotrulos/MSCModLoader#39]
Hey,

I've been trying to figure out how to check if a specific texture file exists in the mod's asset folder. A simple return of a boolean would be great. For now I'm getting errors when the texture is not found.

Thanks!

**Comment by piotrulos** [comment]
Something like this?
```cs
if (File.Exists(Path.Combine(ModLoader.GetModAssetsFolder(this), "texture.png"))
{
    //do something
}
```
File is from `System.IO` namespace

**Comment by Fredrik95** [comment]
Wow, great!

Works perfect! 

Thanks!
