### ISSUE TITLE
Add an Example for ConsoleCommand.Add Method

### ISSUE THREAD

**Issue by Fredrik95** [piotrulos/MSCModLoader#40]
Please add an example for ConsoleCommand.Add Method.

[http://my-summer-car.ml/docs/html/T_MSCLoader_ConsoleCommand.htm](http://my-summer-car.ml/docs/html/T_MSCLoader_ConsoleCommand.htm)

Or for the whole chapter in general, I've been trying to figure out how this works but I'm lost.

Any help would be appreciated, thanks!

/Fredrik

**Comment by piotrulos** [comment]
https://github.com/piotrulos/MSCModLoader/tree/master/Example%20Mods/Example%20mod

**Comment by Fredrik95** [comment]
Thanks!
I managed to figure it out by myself earlier. I didn't, at first, realize that it was a different class. Judging by the example it's good to know that I've done it correctly.
Great example though, you should really add it to the documentation!
