### ISSUE TITLE
Problem with creating folders - ModLoader on MSC for macOS

### ISSUE THREAD

**Issue by TheMorc** [piotrulos/MSCModLoader#43]
So i ported My Summer Car to macOS from Windows by tinkering with Unity Player and eventually i got it working.(i got much better FPS(on Wine i had to use Better graphics setting to get something around 30/40FPS, now i get 75/80/90FPS on Golden Eye) + no mouse bug)

Yesterday i wanted to try ModLoader but got slight problem.
It was generating these folders: https://i.imgur.com/AxrKE6d.png
and i was running it thought Terminal so i can send you log: https://pastebin.ca/3976755

I suspect that the problem is here: `ModsFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), @"MySummerCar\Mods");` i mean that the `\` character between `MySummerCar` and `Mods` is the problem which leads to making those folders, and changing it to `/` can fix it.

Firstly I didn't wanted to create this Issue because i wanted to rebuild the .dll with fix but for some reason it wants Newtonsoft.JSON library which leads to wanting more libraries..(and then MSC saying that another libs are missing) Maybe i am building/doing it wrong.(i was trying to rebuild it in Visual Studio 2017 Community on Windows 8.1, Parallels Desktop with downloaded Unity Tools, to be able to open the project)

I dont know if you will understand this as English is not my primary language.

**Comment by piotrulos** [comment]
It's not designed for other OS than windows. Most likely you will need to rewrite half of the code (not only patcher but also loader itself) Faster method if you want mods and fps, will be bootcamp (dual boot).

**Comment by RedKugelblitz** [comment]
I've tried porting it linux, but it didn't work out so well. It's definetly
worth tinkering with, tho
