### ISSUE TITLE
problem with launching msc patcher on windows 10

### ISSUE THREAD

**Issue by nanukki** [piotrulos/MSCModLoader#44]
So i have a problem with the msc patcher not starting and it says that i do not have the right app to open it even tough it is only an .exe. It would be nice if you would be able to help with this problem.

thanks in advance nanukki.

**Comment by piotrulos** [comment]
did you try "run as admin"? Do you have normal Windows 10 or S version? You should check integrity of windows files in cmd type `sfc /scannow`
