### ISSUE TITLE
It just doesn't work mate

### ISSUE THREAD

**Issue by Whatever123450** [piotrulos/MSCModLoader#45]
Windows 10, fresh install, Steam.

Downloaded latest MSCloader, tried it in several folder locations, tried it in safe mode, but double clicking MSCpatcher.exe just doesn't work. Nothing happens. 
 Tried running a few times -sometimes as administrator- but just end up with a dozen of them in task manager. Can't end process or process tree, even hitting dos prompt and doing a taskkill doesn't end it. 

After lots of testing stuff out, finally got MSCPatcher to run by deleting just MSCLoader.dll . 
Obviously the log reads:
_Check for new version failed with error: MSCLoader.dll_

_MSCPatcher ready!_

_Game folder set to: C:\Program Files (x86)\Steam\steamapps\common\My Summer Car_

_Patch not found, ready to install patch__

Attempting to install responds with the error MSCLoader.dll doesn't exist. Twice. Followed by:
_Cannot create a file when that file already exists.
Please restart patcher!_

Tried fucking around and pulling in MSCLoader.dll into the folder after the patcher is running, but attempting an install just reads:
_An item with the same key has already been added.
Please restart patcher!_

I just want to use the backpack mod again.

**Comment by piotrulos** [comment]
Don't mess with dlls alone or you mess things up.  
I think you need now do this:
Delete entire game managed folder and verify game files on steam. (this will download clean dlls)
Grab clean copy from [here](https://github.com/piotrulos/MSCModLoader/releases/download/v0.3.5/MSCLoader.zip) unpack everything and run MSCPathcer.   
If MSCPatcher hangs at startup make sure all dll files exists, and if it fails with version checking make sure nothing blocks internet access for MSCPatcher.

**Comment by Whatever123450** [comment]
Done as you said, got myself some nice new shiny dll's in the Managed subfolder, slapped that copy of MSCLoader into a new folder and ..it's still the same. Try to use the patcher and nothing happens. Just sits in task manager as a background process and can't be ended. All dll's in the MSCLoader folder present; _Mono.cecil.dll, Mono.cecil.Rocks.dll, MSCLoader.dll, System.Xml.dll and uAudio.dll_ . All 18 dll's that exist by default in the Managed folder have been replaced. 

I'm stumped.

**Comment by piotrulos** [comment]
I'm actually planning release 0.4 today, just doing final testing.   
0.4 has updated patcher with more error checking. If the new patcher will not work for you I think it will be something on your end.   
In meantime you should check integrity of your OS. Open cmd and type `sfc /scannow`

**Comment by Whatever123450** [comment]
Did a system file check for a laugh as you suggested, no problems popped up. I'll keep an eye out for your update

**Comment by Whatever123450** [comment]
Mystery. Still doesn't work with 0.4. 

Same old problem, if I run it it just sits in task manager being unremovable. If I move the MSCLoader.dll out of the folder I can at least run the patcher - not that's of any use without the dll but still - except now it crashes when attempting to find the MSC folder.

**Comment by piotrulos** [comment]
Two things I only think you have.
Permission problems (if you are doing this on Program Files, this folder is protected by Windows) Try other drive that C: (also force patcher to run as admin)

Second cause: You have corrupted .net framework 4 install or any .net library.

**Comment by piotrulos** [comment]
Also third thing but mostly unlikely, your pc can't access http://my-summer-car.ml/docs/ for version check or reads garbage from that website.

**Comment by Whatever123450** [comment]
Huh, your first idea fixed it. Must be some kind of wacky permission problem 'cos running the patcher from a second hard drive did the trick. How queer. Thanks bud, really stupid problem you solved there. <3
