### ISSUE TITLE
Bug: Console font size not applied on game start

### ISSUE THREAD

**Issue by Fredrik95** [piotrulos/MSCModLoader#49]
When changing the console font size in the ModConsole settings, the font size doesn't update when relaunching the game.

Exiting to main menu changes the font, but still not saved after restarting.

**Comment by piotrulos** [comment]
It should save, if something is broken delete file `Mods\Config\MSCLoader_Console\settings` maybe it will fix this.

**Comment by Fredrik95** [comment]
I tried that and reinstalling Mod Loader, didn't help. The console size is saved correctly.

**Comment by piotrulos** [comment]
Looks like I found problem, this is a bug will be fixed in next update

**Comment by Fredrik95** [comment]
Alright, thanks for the quick answer!
