### ISSUE TITLE
Modloader ready text stays up in the left corner ingame.

### ISSUE THREAD

**Issue by haverdaden** [piotrulos/MSCModLoader#5]
In the newest version of MSC and experimental build the "modloader ready" text seems to stay in the left upper corner even when game is fully loaded.

Example: http://i.imgur.com/pVncAGd.jpg

I've tried to opt out of beta. 
Deleted managed folder.

Still doesn't wanna go away ingame :/

**Comment by piotrulos** [comment]
It looks like new game update changed something, this gameobject that has this text should destroy if scene is not main menu.

Will check that.

**Comment by haverdaden** [comment]
Alright great. Oh and btw you could put a warning text on racedepartment until it's fixed.

**Comment by piotrulos** [comment]
Ok, this is weird bug. That text dissapear when you start satsuma engine.
This will take some time, I need to found what the hell is going on.

**Comment by haverdaden** [comment]
Erm strange.. :S

**Comment by piotrulos** [comment]
Ok, finally found this bug. 
For whatever reason, a function where MSCLoader is hooked, is now called twice by game in main menu.  
This created one text on top of another, and after loading game only one was destroyed.

Just fixed it by checking if status text exists before creating it.
