### ISSUE TITLE
Doesn't open anymore

### ISSUE THREAD

**Issue by PasimkNemokamai2017** [piotrulos/MSCModLoader#50]
#### Info
* **OS version/build:**  Windows 10 Pro 1803 17134.48
* **Architecture:** 64bit
* **MSCLoader version:** 0.4.2
* **Type of issue:** Crash

#### Description
Yesterday I was using 0.4.1 without problem.. Today I got update message to update loader to 0.4.2.. When I updated ModLoader.. Loader doesn't open anymore.. I open Task manager process.. I see ModLoader trying to open but after some seconds its gone from process.. I tried re-download and restart PC but still doesn't open

**Comment by piotrulos** [comment]
Please redownload and report if this still happens

**Comment by piotrulos** [comment]
But unpack this into clean folder, or delete MSCFolder.txt from current unpacked folder, it was accidentally added into package, and works only if someone has same MSC instalation as mine.

**Comment by PasimkNemokamai2017** [comment]
Thanks for fast fix! Now everything working fine again.. Thanks again! ;)
