### ISSUE TITLE
Add an Example for Mod.OnGUI Method

### ISSUE THREAD

**Issue by tommojphillips** [piotrulos/MSCModLoader#51]
Please add an example for Mod.OnGUI Method.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://my-summer-car.ml/docs/html/M_MSCLoader_Mod_OnGUI.htm

**Comment by piotrulos** [comment]
It's normal unity class, not related to msc.

**Comment by tommojphillips** [comment]
Thanks @piotrulos
