### ISSUE TITLE
It is not using the internet to connect to steam for the update

### ISSUE THREAD

**Issue by GodsBadAssBlade** [piotrulos/MSCModLoader#52]
I've managed to get it running on offline mode but that didn't allow the mods to be registered, and when i tried to move around or do anything it would completely ignore all my buttons except the windows button. Now i'm trying to sign into steam for the update/"update" it keeps giving me the retry connection, and i know it's the app that is not using the internet because i can access the internet and 
when i try the help with sign in it says page cannot be reached, and yes I have given it admin permissions. Any way to fix this?

Windows 10 v1803 64 bit

MSCLoader v0.4.3

If this can be fixed that would be great.
Cheers, mate

**Comment by piotrulos** [comment]
Sounds like steam problem, not mod loader.

**Comment by GodsBadAssBlade** [comment]
I can connect to steam just fine, but when using the modloader it won't connect to steam at all, it just loads up the sign in popup. Any recommendations at all?

**Comment by piotrulos** [comment]
Are you sure you have mod loader and not some fake thing? There is no "sign in popup" in mod loader. 

You just install mod loader and run game normally from steam.

**Comment by piotrulos** [comment]
post patcher log here.

**Comment by GodsBadAssBlade** [comment]
Loaded saved MSC Folder: C:\Program Files (x86)\Steam\steamapps\common\My Summer Car
Found mods folder in: C:\Users\*************\Documents\Mysummercar\Mods
Found mods folder in: C:\Users\*************\AppData\LocalLow\Amistech\My Summer Car\Mods
Check for new version failed with error: Unable to connect to the remote server

MSCPatcher ready!
==============
Game folder set to: C:\Program Files (x86)\Steam\steamapps\common\My Summer Car

Newest patch found, no need to patch again



I used * to hide my user name, and had to type this all down because i couldn't copy and paste for some reason :\ hope it helps though!

**Comment by piotrulos** [comment]
It appears to be patched correctly, but something blocking access to check for new version (firewall or your internet settings, this may be a clue)

Try run game directly from exe without steam C:\Program Files (x86)\Steam\steamapps\common\My Summer Car\mysummercar.exe

There will be warning about no steam, but mods should work.

**Comment by piotrulos** [comment]
I think you need configure controller first in menu. There is no dynamic switching between controller and keyboard. And not everything can be rebind to controller this game has poor controller support.

**Comment by GodsBadAssBlade** [comment]
Yeah I know, I'm actually working on a controller configuration for it on steam and so far most of the driving aspect is mostly finished, now I just need to fix the walking aspect. But I have a keyboard and mouse too, and the modloader launched MSC wont let me move or look around when i press continue, and I know that it's not frozen or lagging because i see shadows moving and givin enough time I die because those "punks" run me over lol, so any suggestions on that? And thank you for taking so much time out of your day to help me resolve these problems!

**Comment by piotrulos** [comment]
Most likely one of your mods causing that, you need to find which mod and then report that to mod creator.

**Comment by GodsBadAssBlade** [comment]
Ok, I'll go check that out in a quick minute. But what should I do if it isn't the cause?
