### ISSUE TITLE
GUI Combo box?

### ISSUE THREAD

**Issue by Pete9xi** [piotrulos/MSCModLoader#53]
Please read FAQ before!
#### Info
* **OS version/build:** (Windows 10 Home, Version: 10.0.17134 Build: 17134)
* **Architecture:** (x64)
* **MSCLoader version:** (v4.3.)
* **Type of issue:** suggestion 

#### Description
Hi just wondering if there would be a way to add a combo(Dropdown) box to the GUI options?
No biggy just would be a useful GUI element for working with lists ect

#### Attachments
NONE

**Comment by piotrulos** [comment]
Not possible in this old version of engine. Dropdown UI was added in 5.3 i think.
So until dev update game to higher engine version (which will probably never happen) there will be dropdowns.
