### ISSUE TITLE
Example for Mod.hasUpdate Property

### ISSUE THREAD

**Issue by Pete9xi** [piotrulos/MSCModLoader#54]
Hi Piotrulos, how do you go about implementing the has update value, is there any examples of how to do this? 
i have tired writing c#.net webclient script to fetch a file containing the latest update version and comparing that as a string but i ran into errors on the mod console am i other thinking this?  
Help Topic: http://my-summer-car.ml/docs/html/P_MSCLoader_Mod_hasUpdate.htm

**Comment by piotrulos** [comment]
This is internal read-only value managed by modLoader itself.  
You can't change this value.   
Mod update notification is experimental feature it's using steam for this. More info in pm on discord or rd.

**Comment by Pete9xi** [comment]
Okay that makes sense where can i find this info on discord?
