### ISSUE TITLE
LoadOBJ suggestion

### ISSUE THREAD

**Issue by AndyBeamish** [piotrulos/MSCModLoader#58]
#### Info
* **OS version/build: ** Windows 10
* **Architecture:** 64 bit
* **MSCLoader version:** v0.4.4
* **Type of issue:** suggestion

#### Description
Loading complex models with LoadOBJ can be slow and use a lot of memory on some systems.

Suggest using StreamReader directly instead of StringReader, for example:

`        private static void populateMeshStruct(ref meshStruct mesh)
        {
            using (StreamReader reader = new StreamReader(mesh.fileName))
            {
                string currentText = reader.ReadLine();
...
`
and

`        private static meshStruct createMeshStruct(string filename)
        {
            int triangles = 0;
            int vertices = 0;
            int vt = 0;
            int vn = 0;
            int face = 0;
            meshStruct mesh = new meshStruct();
            mesh.fileName = filename;
            using (StreamReader reader = new StreamReader(filename))
            {
                string currentText = reader.ReadLine();
`
Seems much quicker, with less memory usage, at least on my system anyway (game is on hard drive, not flash)

**Comment by piotrulos** [comment]
LoadOBJ was added from unity library and I didn't touch it. But since I added LoadBundle, LoadOBJ is obsolete, most likely will be removed in future versions.

**Comment by piotrulos** [comment]
But if you want just create pull request for this file, so I can include it.

**Comment by AndyBeamish** [comment]
I could see a need for it: LoadOBJ just needs the object, with LoadBundle you must have Unity installed. Also LoadOBJ is great for very simple mods. I'll try and add the code when I get a moment.
