### ISSUE TITLE
Creating Double money text making fps drop

### ISSUE THREAD

**Issue by Michaelhost1** [piotrulos/MSCModLoader#59]
Info
OS version/build: (ex. Windows 10 1803 17134.65)
Architecture:** (64 bit)
MSCLoader version:** (v0.44) Latest Version
Type of issue:** bug

#### Description
The problems are MSC loader created another money text and the total of our money like the screenshot so because of that it making the game fps dropped to only 20 fps

#### AttachmentPlease attach **output_log.txt** from `mysummercar_Data` folder  s

[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/2301998/output_log.txt)

![untitled](https://user-images.githubusercontent.com/42538207/44334931-142b4180-a49d-11e8-929b-e215cacae658.png)

**Comment by piotrulos** [comment]
This looks like one of your mods have problem, not related to mscloader.
Try disable your mods and then enable them one by one to see whcih one causing this bug.

**Comment by Michaelhost1** [comment]
i had, and also i already re-install it all of them

**Comment by piotrulos** [comment]
Reinstall does nothing when mods are not updated to latest game version.
Based on your output log, the "new hause" throws tons of errors, and the UI bug seems to be related to backpack mod.

**Comment by Michaelhost1** [comment]
i see, i already know the new house errors, but i had no idea about what cause the UI bug thingy better told the creator though about that, hope this helps the others, thanks by the way

**Comment by Michaelhost1** [comment]
but the fps still locked around 20 fps though

**Comment by Michaelhost1** [comment]
i also tried removing the MSC loader patch maybe it's my pc but it's gave me above 20 fps

**Comment by piotrulos** [comment]
According to outputlog you are running msc on integrated intel graphics. This won't get you more fps.

**Comment by Michaelhost1** [comment]
i see, but it ran smootly on v0.43 before this update

**Comment by Michaelhost1** [comment]
i tried your suggestion though and it's kinda increase the fps, weird on previous build it ran smoothly on integrated intel, thanks for the information and suggestion, love your work :D keep it up

**Comment by Michaelhost1** [comment]
hey, could you told the creator of the backpack mod that it creating that bug, i really appreciate it though thanks
