### ISSUE TITLE
Check for pink background and remove it.

### ISSUE THREAD

**Issue by haverdaden** [piotrulos/MSCModLoader#6]
Recently a pink background has been added to the needs attributes. This sometimes pops up when you have a modded game. 

I think it's meant for people cracking the game but now we that own the game can also see it if we have modded the game sometimes. 

Could you try finding the gameobject and removing it on load?

Example: http://i.imgur.com/cRGCRpR.jpg

**Comment by piotrulos** [comment]
I never had this issue, on my modded game.
If this is piracy check, maybe you are running game outside steam?

**Comment by haverdaden** [comment]
You were right. I was running it outside of steam when I was testing my mods. Well atleast that's clear now.
