### ISSUE TITLE
No possibility to enable debugging

### ISSUE THREAD

**Issue by keplusplus** [piotrulos/MSCModLoader#62]
Hey,

thanks for this nice MSC Mod Loader!

When I try to enable debug in the MSCPatcher, the error "No debug files found" appears. I've no chance to enable debugging, because the whole section is not visible.

There is nothing special in the log-tab.

What am I doing wrong?
Thanks!!

------------------ LOG ------------------
Loaded saved MSC Folder: D:\Program Files (x86)\SteamLibrary\steamapps\common\My Summer Car
Found mods folder in: D:\[...]\Dokumente\MySummerCar\Mods

MCSLoader v0.4.6 is up to date, no new version found.

MSCPatcher ready!
-=================-
Game folder set to: D:\Program Files (x86)\SteamLibrary\steamapps\common\My Summer Car

Newest patch found, no need to patch again

**Comment by piotrulos** [comment]
Download full package or select "download advanced files" in launcher to get debug files.

**Comment by piotrulos** [comment]
It was written before Launcher and minimal version to download.

It will be updated, thanks.
