### ISSUE TITLE
[Bug] ".transform" in global variable declaration makes mod unrecognizable.

### ISSUE THREAD

**Issue by Fredrik95** [piotrulos/MSCModLoader#63]
#### Info
* **OS version/build:** Windows 10
* **Architecture:**  64 bit
* **MSCLoader version:** v0.4.6
* **Type of issue:** Bug

#### Description
Using "GameObject.Find("blabla").transform" (specifically ".transform") in global variable declaration (outside method, ie. under "UseAssetsFolder") makes Mod Loader not recognize the mod as a mod. 
See line 24 & 25 in attached file.

Project builds without errors, all references are present. Without those lines, it works ( if I put them in OnLoad() it works also, of course ).

Not a big problem but I thought it was worth mentioning, as it was not clear at first that that was the problem.

#### Attachments
[Wristwatch.zip](https://github.com/piotrulos/MSCModLoader/files/2413454/Wristwatch.zip)

**Comment by piotrulos** [comment]
You cannot use GameObject.Find in costructor or outside method, this will cause UnityException:
`UnityException: Find is not allowed to be called from a MonoBehaviour constructor (or instance field initializer)`
Your mod just crashes because you abused unity API.

**Comment by Fredrik95** [comment]
As I said, it works perfectly just until you reference the transform component. 
I've used Find bunch of times (without .transform), never ever had any problems, errors or crashes. Never even seen that exception, neither in output_log or ModLoader Console. 
So it seems that I CAN use it outside methods, just not transform, and I'd like to know why referencing specifically a transform component would somehow make ModLoader not recognize it as a mod at all, without any other kind of errors or log entries.

**Comment by piotrulos** [comment]
Dude, because this is not allowed by unity api.  
For some reason roslyn compiler doesn't mark this as error (it should). Try the same code in unity, it will fail to compile.  
If you know how constructor works, then you should know why using find outside method will never work.
