### ISSUE TITLE
Got HUGE FPS drop. Help!

### ISSUE THREAD

**Issue by abcd60108** [piotrulos/MSCModLoader#65]
Info
OS version/build: (ex. Windows 10 1809 17763.55)
Architecture:** (64 bit)
MSCLoader version:** (v0.47) Latest Version
Type of issue:** bug

Description
The problem is that the text created another by the MSC loader is just like the screenshot of our money so it makes the game fps drop to only 20 fps

aspp Please attach output_log.txt from mysummercar_Data folder s
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/2553281/output_log.txt)
          
![my summer car 2018_11_6 09_21_08_li 2](https://user-images.githubusercontent.com/25796302/48068610-33b94700-e20e-11e8-9b9f-92fa2e0a6ac3.jpg)

![my summer car 2018_11_6 09_21_10](https://user-images.githubusercontent.com/25796302/48067065-46318180-e20a-11e8-91b3-9260e48af0bd.png)

![my summer car 2018_11_6 09_19_37_li](https://user-images.githubusercontent.com/25796302/48068641-53e90600-e20e-11e8-99f3-1f0e8b63fa98.jpg)

**Comment by piotrulos** [comment]
Reading faq doesn't hurt   
But since you attached log, broken mods are MSCStill, JetSky, EnableApartment and ImproveFPS.   
Remove these mods so your fps go back to normal.

**Comment by abcd60108** [comment]
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/2557225/output_log.txt)

**Comment by piotrulos** [comment]
coffemachine also spams you with errors.

**Comment by abcd60108** [comment]
I already know this will make me drop fps 20

![48067065-46318180-e20a-11e8-91b3-9260e48af0bd](https://user-images.githubusercontent.com/25796302/48166466-9cdeae80-e323-11e8-9f02-80586ab4e526.png)

The previous version does be normal fps 60

**Comment by piotrulos** [comment]
this was broken long time ago, even author says to not install it.

**Comment by abcd60108** [comment]
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/2565600/output_log.txt)

**Comment by abcd60108** [comment]
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/2565686/output_log.txt)
