### ISSUE TITLE
i literally cant pick where my mods are suppose to be help 

### ISSUE THREAD

**Issue by MrTroll2** [piotrulos/MSCModLoader#67]
Info
* **OS version/build:** Windows 10 
* **Architecture:** 64bit 
* **MSCLoader version:** Latest version as of typing this. 
* **Type of issue:** bug

 I literally can't change my mods location, if i try to switch to documents where the mods are, it will instantly change back to the game folder, and that causes it not to load any mods for some reason.

**Comment by piotrulos** [comment]
My crystal ball stopped working.
