### ISSUE TITLE
Download Link Not Oppening

### ISSUE THREAD

**Issue by Aron2004** [piotrulos/MSCModLoader#69]
The https://github.com/piotrulos/MSCModLoader/releases/download/v0.4.7/MSCLoader_Full.Package.zip
Doesn't Work For Me. Please Help!!

**Comment by piotrulos** [comment]
Does work for me. Please not help!!

**Comment by n0tic** [comment]
ufile(dot)io/afi1d

Downloadable file will be automaticly removed after 7 days. 
This is not a bug or anything that @piotrulos can control.
You need to check your browser settings / extensions.

GLHF.
