### ISSUE TITLE
[Question]How to install mods with my summer car multiplayer mod?

### ISSUE THREAD

**Issue by SkyCZ** [piotrulos/MSCModLoader#70]
Please read FAQ before!
#### Info
* **OS version/build:** Windows 10.0 build 17763
* **Architecture:** 64 bit
* **MSCLoader version:** 0.4.7
* **Type of issue:** suggestion/question

#### Description
I have a question onto how to run mods using mod loader and run multiplayer mod (https://github.com/MSCMP/MSCMP) at the same time 

#### Attachments

**Comment by piotrulos** [comment]
Not possible, because every mod would require separate syncing between clients. 
Multiplayer mod is separate thing.

**Comment by SkyCZ** [comment]
What if every client on the "server" will have the mods?

**Comment by piotrulos** [comment]
Nothing will happen or game will crash (based on what mod does), because Multiplayer mod doesn't sync any mod content, it doesn't even sync all stock parts yet.
