### ISSUE TITLE
Problem with mod loader and  the modloader disabling a mod

### ISSUE THREAD

**Issue by Hallamekk** [piotrulos/MSCModLoader#71]
hey!
I have a problem with my summer car mod loader. I bougth my summer car on steam, and i havent had a problem with mods or the mod loader before today. I downloaded and installed the latest version. But when i try to run it, it says new version is availible : v0.4.7a, wanna check it out? i then press yes. it then takes me to a screen where it shows me update history of the mod loader.  down in the bottom it says no new update found. and i click on lunch patcher. but then the same message i got earlier pops up again. it says new version is availible : v0.4.7a, wanna check it out? if you click yes you get to the same version history again. but if i click no i get to the regular mod loader screen. And from there everything works like normal. when i fire up the game in the top left corner it says that the modloader v0.4.7a is up to date. like normal. 

But here is my biggest problem. I downloaded the newest version of the dustman mod. Witch have been working perfectly for me before. i installed it now, and i know i installed it correctly. But down in the left corner it tells me error: plymouth.dll doesnt look like a mod, remove this file from mods folder!

 its only this mod thats causing issues, my other mods work like normal. 
I tried re-installing both the mod and the mod loader. but still doesnt work. i also tried deleting all game files and uninstallig the game on steam. Then re installing it but still the same problem.  

Thanks.

**Comment by piotrulos** [comment]
Click this button to fix that loop problem with "new version found"
![fix](https://user-images.githubusercontent.com/4009096/52167852-d3a94280-2721-11e9-89ec-b7753b793f8f.png)

**Comment by Hallamekk** [comment]
that worked! Thanks :)
