### ISSUE TITLE
The Dustman Mod 

### ISSUE THREAD

**Issue by SRTXGAMES** [piotrulos/MSCModLoader#72]
![msc](https://user-images.githubusercontent.com/47344369/52254119-d2227a80-28d9-11e9-86ee-0bd716919885.jpg)

#### Info
* **OS version/build:** Windows 10 
* **Architecture:** 64 bit?)
* **MSCLoader version:** (ex. v0.4.7a)
* **Type of issue:** bug/crash/suggestion (remove unnecessary)

_The New Dustman Mod No Longer Shows Up In Game And The Modloader Console Said Plymouth Doesn't Look Like A Mod. The Dustman Has Been Working Since It's Release Back At Christmas In 2018 And Had No Problem Until Now._  

#### Description
Describe your problem here with reproduce steps  
Useless reports without any details will be closed without replying.

#### Attachments
Please attach **output_log.txt** from `mysummercar_Data` folder  
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/2830803/output_log.txt)
Screenshoots related to your issue:
![msc](https://user-images.githubusercontent.com/47344369/52254119-d2227a80-28d9-11e9-86ee-0bd716919885.jpg)

**Comment by piotrulos** [comment]
I'm not author of this mod, report this to author of this mod not me.
