### ISSUE TITLE
Can't open the patcher

### ISSUE THREAD

**Issue by panos4512** [piotrulos/MSCModLoader#73]
#### Info
* **OS version/build:** Windows 10 Home 1809 17763.316
* **Architecture:**  64 bit
* **MSCLoader version:** v0.4.7a
* **Type of issue:** 

#### Description
I can't open the patcher.exe at all in this update.
What should i do?

**Comment by demonslayer600** [comment]
I am having the same issue with the MSC Patcher not running. I did a troubleshoot and it says it is not compatible with Windows 10, please advise?

**Comment by piotrulos** [comment]
Unpack all the files, everything is in a FAQ.

**Comment by panos4512** [comment]
i have run a debugger from the zip file and it says that access to the registry path is denied.
What should i do then?
