### ISSUE TITLE
[Question] Chosen Mods path

### ISSUE THREAD

**Issue by Pickysaurus** [piotrulos/MSCModLoader#74]
Hi there, 

I was wondering if you could provide me with some information on how elements of MSCModLoader work. 

My questions are (hopefully) simple:

1) Is there an INI file or some other way to access which folder the player has selected to manage their mods from? Or is there a file placed in the chose mods folder that can be detected?
2) To play with mods loaded through MSCModLoader, must you start the game via the loader or can you do it from the EXE/Steam?
3) Can functions from the loader be run from command line, I did see an API article on the wiki but it doesn't look like you've had the chance to write it yet? 
4) If MSCModLoader is correctly installed, MSCLoader.dll should be found inside `{GAMEDIR}\mysummercar_Data\Managed` is that correct?

If possible, could piotrules or one of the team here send me a message on Discord (@Pickysaurus#1677) or Nexus Mods (Pickysaurus)? 

Thanks,

Mike

**Comment by piotrulos** [comment]
1. No, it's internal only, modders has access to assets and config folders via API, so you don't need to know the path.
2. Steam
3. What do you mean?
4. There is many more libraries put in managed folder.

**Comment by Pickysaurus** [comment]
Thanks for the answers, as we're speaking on Discord now we can close this issue :)
