### ISSUE TITLE
MSCLoader_Launcher

### ISSUE THREAD

**Issue by paulius122** [piotrulos/MSCModLoader#75]
evry time i try to run:MSCLoader_Launcher it says:Error the remote server returned an error: (403) Forbidden,
here are some images of the errors:https://github.com/piotrulos/MSCModLoader/files/3050409/ErrorImages.zip)

contact me and please help  me solve  this

**Comment by piotrulos** [comment]
I didn't see any problem server side, you should check your firewall/antivirus if it doesn't block access to http://my-summer-car.ml 
Only 403 errors in logs I see is Directory listing, but that's normal thing, not related to launcher.
