### ISSUE TITLE
MSC Loader dont working on 23.04 update.

### ISSUE THREAD

**Issue by AnteyR** [piotrulos/MSCModLoader#78]
Windows
64bit
MSC Loader 0.3.5-0.4.7a

More people says 0.3.5 is working on new update msc, Improve FPS is opening but dont working.
Im trying on all version of loader and dont working. 
My ImproveFPS mod on 0.4.7a dont working, you must do a msc loader update bro, Please :D

**Comment by piotrulos** [comment]
There is no such official update named 23.04.

**Comment by AnteyR** [comment]
I mean the newest update with uncle and suski

**Comment by piotrulos** [comment]
As I said it's not official update yet, it's closed experimental update. And if you would read FAQ you will know that experimental updates are not supported by mod loader (and never will be)

**Comment by AnteyR** [comment]
I read FAQ and i only see faq about game, Like : Huge FPS DROP! HELP!
Soo, Wee must wait for the msc update when the newest update with uncle dont be in experimental, yes ? 
But some mods in 0.3.5 working

**Comment by AnteyR** [comment]
Mów mi odrazu że ty polak bo ja po angielsku pisać nie umiem :D
