### ISSUE TITLE
How can I use courtine and monobehavior class ?

### ISSUE THREAD

**Issue by haverdaden** [piotrulos/MSCModLoader#8]
Hello :)

I've been using Timers to execute methods after some seconds but I feel that StartCourtine would be easier to use.

How can I use the monobehavior class in my mod class and use stuff like courtines ? :)

**Comment by piotrulos** [comment]
You can use as many monobehaviour class as you want. You can call them from Mod class or create a GameObject and attach monobehaviour class to it (it will work as it works in unity)

Something like this: 
* Create monobehaviour class (if you are using VS templates there is a template for this)
* In mod class Create gameobject in OnLoad (or Update if this need to be executed after key press)   
* `GameObject go = new GameObject();`
* it's good to give gameobject a name if you want find it later and prevent duplicates `go.name = "Something";`
* Attach monobehaviour class to it `go.AddComponent<SomeClass>();`
* And that's it, this should execute as normal monobehaviour class (you can check if Start() or Awake() is executed by printing something in console). You can use in this class anything you want like Coroutines and anything from unity you found on docs.unity3d.com (but remember to switch to 5.0 documentation)

Remember also that any errors will not be catched by MSCLoader, you need to create custom "try catch" to debug any errors.

**Comment by haverdaden** [comment]
Thx :) 👍
