### ISSUE TITLE
MSCLoader v1.0 Mod Settings Button disapears apon saving game.

### ISSUE THREAD

**Issue by tommojphillips** [piotrulos/MSCModLoader#80]
Please read FAQ before!
#### Info
* **OS version/build:** (ex. Windows 10 1709 16299.248)
* **Architecture:** (32 or 64 bit?) 64bit
* **MSCLoader version:** (ex. v0.4) v1.0
* **Type of issue:** bug

#### Description
Describe your problem here with reproduce steps  
Useless reports without any details will be closed without replying.

I loaded my < v9.5.2019 save by continuing on the main main scene. I then proceeded to fill my Satsuma at the store and then went to save. Mod Settings button disembarked as soon as the Main Menu Scene loaded.
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/3168506/output_log.txt)

#### Attachments
Please attach **output_log.txt** from `mysummercar_Data` folder  
Screenshoots related to your issue.

**Comment by piotrulos** [comment]
hmm, I cannot reproduce that bug, it shows fine for me when saving or going back to menu. Your log also doesn't show any errors.
I will need to look at this more.
BTW. Mod settings still can be opened using old ctrl+m shortcut.

**Comment by piotrulos** [comment]
I made a small fix that may fix that.     
Also make sure that you accidentally didn't disable that button. It's in main settings module    
`ctrl + m > show core modules > Main settings > Show mod settings button in bottom right corner`

**Comment by tommojphillips** [comment]
I never touched the settings since the v1.0 update. i've just tested the 1.0.1 update and have realised that upon loading mscloader initially, it apparently doesn't check if the setting is true. (as the sc shows).. So it disappearing when exiting to menu or saving was correct. 

![Desktop Screenshot 2019 05 13 - 05 22 22 38](https://user-images.githubusercontent.com/39871058/57586845-1cea0900-753f-11e9-818d-880119641efb.png)

**Comment by piotrulos** [comment]
for me it works fine, try to verify modloader files in launcher and also try to delete config files in mscloader_settings folder.
