### ISSUE TITLE
Game files detected, aborting! RTFM and "did you read the manual?" errors when using loader or patcher

### ISSUE THREAD

**Issue by NowThisGuy** [piotrulos/MSCModLoader#81]
whenever I use either the Launcher or Patcher it just gives me these errors

**Comment by piotrulos** [comment]
Yeah read the freaking manual, that clearly says "do not unpack into game folder"

**Comment by NowThisGuy** [comment]
> Yeah read the freaking manual, that clearly says "do not unpack into game folder"

I didn't unpack it into the game folder though

**Comment by piotrulos** [comment]
Prove it.
