### ISSUE TITLE
MSC Loader Crash

### ISSUE THREAD

**Issue by Damian-Gaffey** [piotrulos/MSCModLoader#82]
Please read FAQ before!
#### Info
* **OS version/build:** Windows 10 1803 17134.765
* **Architecture:** 64 bit
* **MSCLoader version:** 1.0.1
* **Type of issue:** crash

#### Description
Load MSC with mod loader spawn into game it loads mods then crashes with this line: MSCLoader ERROR: Mod MSCLoader_Settings throw an error!
have tried loading without mods aswell with no improvement also everytime I spawn in game everything on car is unbolted so have to rebolt everything before I can move onto where I was.
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/3219625/output_log.txt)

#### Attachments
Please attach **output_log.txt** from `mysummercar_Data` folder  
Screenshoots related to your issue.

**Comment by piotrulos** [comment]
For me it looks like assets file for settings is wrong.   
In launcher you should use option to verify modloader files (or grab full package from github), and in the patcher do full repatch by clicking remove mscloader and then install mscloader.

**Comment by Damian-Gaffey** [comment]
Ok, Great that worked thanks for your help keep up the good work :)
