### ISSUE TITLE
Add an Example for Settings Class?

### ISSUE THREAD

**Issue by Krutonium** [piotrulos/MSCModLoader#84]
Please add an example for Settings Class.

Basically, I have no idea how to actually add settings to my mod. A usage example would be *super* helpful.

Help Topic: http://my-summer-car.ml/docs/html/T_MSCLoader_Settings.htm

**Comment by piotrulos** [comment]
There are examples, just click on specified methods you want to see.

**Comment by Krutonium** [comment]
I mean like... How?

The documentation doesn't show _how_ to put the code together.

**Comment by piotrulos** [comment]
really? It's clear how to use it.
http://my-summer-car.ml/docs/html/M_MSCLoader_Settings_AddButton.htm e

**Comment by Krutonium** [comment]
...Apparently I was completely blind and stupid. Thanks for putting up with me!
