### ISSUE TITLE
MSCLoader handles extreme widescreen poorly

### ISSUE THREAD

**Issue by Krutonium** [piotrulos/MSCModLoader#85]
Please read FAQ before!
#### Info
* **OS version/build:** Windows 10 1903 18362.175 
* **Architecture:** 64 bit
* **MSCLoader version:** 1.0.1
* **Type of issue:** bug

#### Description
Running the game at extreme widescreen ratios makes the modloader UI extremely huge, preventing things like accessing mod settings (they go off the top and bottom of the screen)

#### Attachments
![20190624004314_1](https://user-images.githubusercontent.com/3945538/59992391-99c9d180-9619-11e9-9a1e-990c5f3ee159.jpg)

**Comment by piotrulos** [comment]
There is a way to fix scaling for that type of widescreen, but It may break scaling for normal resolutions (this is 5 year old version of engine).

I can add this as option into settings, so players with that type of widescreen can toggle scaling.

**Comment by Krutonium** [comment]
Thank You!
