### ISSUE TITLE
Add an Example for LoadAssets.LoadBundle Method

### ISSUE THREAD

**Issue by vWernay** [piotrulos/MSCModLoader#86]
Plz add an example for LoadAssets.LoadBundle Method

I put the code in Visual Studio and when I open the game appears: Error mod satsumaTURBO thwow an error!
Details: Obejct reference not set to an instance of an object in Void()OnLoad

Help Topic: http://my-summer-car.ml/docs/html/M_MSCLoader_LoadAssets_LoadBundle.htm

**Comment by piotrulos** [comment]
just few clicks away you have https://github.com/piotrulos/MSCModLoader/wiki/How-to-create-and-use-Asset-Bundles

**Comment by vWernay** [comment]
> just few clicks away you have https://github.com/piotrulos/MSCModLoader/wiki/How-to-create-and-use-Asset-Bundles

I did it but I think the problem is the code look: http://prntscr.com/o63o1o

**Comment by piotrulos** [comment]
At first look code looks ok, you should use Debugging to see in which line that error happens.

**Comment by vWernay** [comment]
> At first look code looks ok, you should use Debugging to see in which line that error happens.

Ok, very thx
