### ISSUE TITLE
Some Values Get Reset/Overriden by Game when changed by mod

### ISSUE THREAD

**Issue by DonnerPlays** [piotrulos/MSCModLoader#89]
Sorry if it's the wrong place to ask about this.

I'm currently trying to make a Turbo Charger mod. 
I want to change the power multiplier depending on the current rpm.
So for now i wanted to do it like this : at 2000rpm begin to check... every +100 rpm (so 2100,2200) increase the power multiplier by lets say 5% (so power multiplier * 1.05).
The Problem is as soon as i start the car the value satsumaDriveTrain.powerMultiplier is reset to 1 (when i set it to 2 for example in void Update() before).

i am able to change "fixed" values like disabling revLimiter. But it wont work with stuff that changes over time.

is there something I'm missing?

**Comment by piotrulos** [comment]
You need to find correct source playmaker and change value there.

**Comment by DonnerPlays** [comment]
Ahh i thought for DriveTrain you don't need PlayMaker, alright gonna try this. Thanks :)

**Comment by DonnerPlays** [comment]
Thank you @piotrulos . I got it working, it will still need alot of changes to make it more realistic but it works.

This is how i did it (if somebody needs it ):
1) Inside OnLoad() add:
`satsuma = GameObject.Find("SATSUMA(557kg, 248)");
            satsumaDriveTrain = GameObject.Find("SATSUMA(557kg, 248)").GetComponent<Drivetrain>();`
-> is needed for engineRPM and such.

2) declare a private variable inside your Class: private FsmFloat _powerMultiplier;

3) Inside OnLoad() Function add:
`foreach (var playMakerFloatVar in PlayMakerGlobals.Instance.Variables.FloatVariables)
            {
                switch (playMakerFloatVar.Name)
                {
                    case "EnginePowerMultiplier":
                       
                        _powerMultiplier = playMakerFloatVar;
                        break;
                }
            }`
-> this will go throuth all PlayMaker Float Values and finds "EnginePowerMultiplier"

4) Inside Update() Function add:
`if(engineRPM >= 2000)
            {
                _powerMultiplier.Value = 1.1f;
                if(engineRPM >= 2400)
                {
                    _powerMultiplier.Value = 1.3f;
                    if (engineRPM >= 2800)
                    {
                        _powerMultiplier.Value = 1.5f;
                        if (engineRPM >= 3200)
                        {
                            _powerMultiplier.Value = 1.7f;
                            if (engineRPM >= 3600)
                            {
                                _powerMultiplier.Value = 1.9f;
                            }
                        }
                    }
                }
            }
            else
            {
                _powerMultiplier.Value = 1;
            }`
-> this is just a basic way of doing it by just increasing the multiplier by 0.2 each time the rpm is =>.
-> engineRPM = satsumaDriveTrain.rpm;

Hope it helps someone.
