### ISSUE TITLE
[Suggestion] Unload mods in main menu.

### ISSUE THREAD

**Issue by haverdaden** [piotrulos/MSCModLoader#9]
Right now we are not able to use the OnLoad() method properly when the player goes saves or goes to the menu as it will not be run again.  

The workaround for that now is ofc to check what level is loaded in Update() and reset variables to reload mod.

Best thing would be if this check would be checked in the modloader :D

Looking at the planned features I was not sure this was being included in the "Allow mods load in main menu...".

Maybe there could something like this:

```
if(Application.loadedLevel != 3 && modsLoaded)
{
UnloadMods();
}

if(Application.loadedLevel == 3 && !modsLoaded)
{
LoadMods();
}
```
But I guess the modloader might have a much more complex method when loading mods and this may not work with modloader. But you get what I mean :)

**Comment by piotrulos** [comment]
I'm actually working on Unloading Mods:) 

But loading mods is still unchanged from 0.1 code.
For now it looks like this
```
            if (!IsModsDoneLoading && Application.loadedLevelName == "GAME")
            {
                // Load all mods
                ModConsole.Print("Loading mods...");

                LoadMods();
                ModSettings.LoadBinds();
                IsModsDoneLoading = true;
                ModConsole.Print("Loading mods complete!");
            }
```
And loaded mods is stored in List `List<Mod> LoadedMods;` 
I can just clear list but console and settings also are "Mods", and there is also Console commands and keybinds in separate lists,

I can change loading mods completely, but it will probably break all current mods.
