### ISSUE TITLE
Multiple Questions about making a Mod

### ISSUE THREAD

**Issue by DonnerPlays** [piotrulos/MSCModLoader#90]
Another question about making a mod :)

1) How do you check for PlayMaker Events getting triggered? -> I want to check if the nos was enabled

I can't find a way how you can work with a PlayMaker Event, i also can't find any variable (Like with if player is in car) for checking the status of the nos.

2) how do you make selfmade assets have physics (gravity, pickup by player, collision). I can't find a way to do it.

in the Mod Api the deprecated function "LoadObj" has a parameter collider and Rigidbody but how can i do it with LoadBundle.

also the function MakeGameObjectPickable doesn't seem to work for me. Maybe because i don't have any physics?

3) How do you make it possible to "install" a part on the car?
Like in my case i have a turbocharger which should be connected to the exhaust system but i didn't find a way to tell the game "this part goes there and has screws there and there"

Hope someone can answer these questions :)

**Comment by DonnerPlays** [comment]
4) I also cannot get the ModAudio to load a .wav file.



This is in my OnLoad Function:
`
turbocharger_sound_loop_path = Path.Combine(ModLoader.GetModAssetsFolder(this), "turbocharger_loop.wav");
ModAudio test = new ModAudio();
 test.LoadAudioFromFile(turbocharger_sound_loop_path", true, false);
`
The Path is correct. 
I always get this error: Mod xyz throw an error!
Details: Object reference not set to an instance of an object in Void LoadAudioFromFile

I'm probably missing something. It's the first time for me working with unity.

**Comment by piotrulos** [comment]
I think you should start with something simple and learn how unity api works.
First and big mistake is that you are using new keyword for a monobehaviour class. This is a big mistake because there is no constructor in that class.
You can only access monobehaviour class instance by using GetComponent (or AddComponent if you need a new instance).

**Comment by DonnerPlays** [comment]
Yeah already noticed that.

I got the audio working and I'am now working on getting it to sound good.
I Also got the model positioned where it should be, but i still have to find a way to make it "installable" with bolts.

**Comment by piotrulos** [comment]
basically if you are working on prefabs you don't even need to use modAudio. 
Just do everything in prefab including audio.

But the question I have, do we really need 50th turbo mod?

**Comment by DonnerPlays** [comment]
Well, now i feel stupid ^^.

I never saw a turbo mod on racedepartment, guess i should have googled "My Summer Car turbo" before :D

Oh well atleast i can learn a little bit by doing it myself.
