### ISSUE TITLE
Thinks steam client doesn't exist.

### ISSUE THREAD

**Issue by topper4125** [piotrulos/MSCModLoader#91]
Please read FAQ before!
#### Info
* **OS version/build:** Windows 10 
* **Architecture:** 64 bit
* **MSCLoader version:** 1.11
* **Type of issue:** bug

#### Description
I'm Running version 1.1.1 and I have been getting an error for the last few days that says:

MSCLoader ERROR: Steam client doesn't exists.

Tried the following things:

1) Verified game files via Steam Properties
2) Removed MSCLoader
3) Re-Installed MSCLoader
4) Rebooting Machine

Mods are stored in C:\Users\<name>\Documents\MySummerCar\Mods\
Game is located in D:\Steam\steamapps\common\My Summer Car\
ModLoader located at D:\Portable\MSC Mod Loader\

Screenshot: https://i.imgur.com/uyL13G7.jpg

#### Attachments ####

[https://pastebin.com/A0riGmNv](https://pastebin.com/A0riGmNv)

**Comment by topper4125** [comment]
Thanks for the support.

**Comment by Aberro** [comment]
Same.

**Comment by Aberro** [comment]
Steam overlay from running game (with no-steam error):
https://imgur.com/a/rMEp37C
Purchase receipt:
https://imgur.com/a/sV2pcsc
