### ISSUE TITLE
Fork for another Unity Game

### ISSUE THREAD

**Issue by mukoladeath** [piotrulos/MSCModLoader#93]
Hi,
You make really great work, Thanks
Just want ask, before dig in code,
theoretically, Can I take sources (MscLoader\PhiScript\PBLoader) for reverse and make my fork-mod-loader, for example, for LongDark or another unity game? is it doable?

Best Regards,
M.

**Comment by piotrulos** [comment]
Everything is in license terms (permissions and conditions)
https://github.com/piotrulos/MSCModLoader/blob/master/LICENSE 
Basically in short words, you can modify, distribute etc but it need to be open source and released on the same license.

**Comment by mukoladeath** [comment]
got it, thanks
