### ISSUE TITLE
Satsuma hood uninstalls on save load with mod loader installed

### ISSUE THREAD

**Issue by Nerezza** [piotrulos/MSCModLoader#95]
Please read FAQ before!
#### Info
* **OS version/build:** Windows 10 17134
* **Architecture:** 64-bit
* **MSCLoader version:** 1.1.1
* **Type of issue:** bug

#### Description
First let me say I've been sitting on this bug for a couple weeks now, because I haven't been able to find any obvious causes for it. Ultimately the only way to stop this from happening was to uninstall the mod loader patch, as even with no mods installed the patch will cause the following bug.

In both the current MSC stable and experimental builds the stock hood of my Satsuma pops off every time I load the game. The bolts remain all tightened, so I can just place the hood right back onto the car without having to re-tighten the bolts. I've confirmed and re-confirmed over multiple RL days that the hood is installed correctly through MSCEditor, and there are no relevant problems with the car. If I uninstall the mod loader patch my car's hood remains attached when I load the game. Re-installing it and removing all mods causes the issue to happen again on load, so the only trigger I've found for this issue is the mod loader patch itself.

#### Attachments
**output_log.txt** coming later, I don't think the current log has the patcher enabled and I don't have the time atm the make sure the environment is ideal for making a good log of the issue.

**Comment by piotrulos** [comment]
cannot reproduce, not related to loader.

**Comment by Nerezza** [comment]
"Clean" output_log.txt attached. I removed my mods folder temporarily to generate one with the patcher installed and no mods active, re-enabled write on meshsave.txt, re-confirmed in the save editor that the hood was installed correctly, then confirmed in-game that the hood had come off on load.
I'm also up to version 1.1.2 of the mod loader now.
